/**
 *
 * $Id$
 */
package voiceDsl.validation;


/**
 * A sample validator interface for {@link voiceDsl.Audio}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AudioValidator {
	boolean validate();

	boolean validateDontBargeIn(boolean value);
	boolean validateTts(String value);
	boolean validateSrc(String value);
}
