/**
 *
 * $Id$
 */
package voiceDsl.validation;


/**
 * A sample validator interface for {@link voiceDsl.Grammar}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GrammarValidator {
	boolean validate();

	boolean validateMode(String value);
	boolean validateSrc(String value);
	boolean validateExpr(boolean value);
}
