/**
 *
 * $Id$
 */
package voiceDsl.validation;

import org.eclipse.emf.common.util.EList;

import voiceDsl.Audio;
import voiceDsl.Condition;
import voiceDsl.Grammar;

/**
 * A sample validator interface for {@link voiceDsl.InputElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InputElementValidator {
	boolean validate();

	boolean validateGrammatics(EList<Grammar> value);
	boolean validateName(String value);
	boolean validateMaxNoInput(int value);
	boolean validateMaxNoMatch(int value);
	boolean validateMaxAttempts(int value);
	boolean validateInitialAudios(EList<Audio> value);
	boolean validateNoMatchAudios(EList<Audio> value);
	boolean validateNoInputAudios(EList<Audio> value);
	boolean validateMatchAudios(EList<Audio> value);
	boolean validateConditions(EList<Condition> value);
}
