<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="voiceDsl" nsURI="http://www.isb.com/bks/ivr/voice/dsl/VoiceDsl"
    nsPrefix="voiceDsl">
  <eClassifiers xsi:type="ecore:EClass" name="InputElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="configuration" eType="#//Configuration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="grammatics" eType="#//Grammar"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="audios" eType="#//Audios"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Grammar">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="builtin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="src" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Configuration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxNoInput" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxNoMAtch" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxAttempts" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Audios">
    <eStructuralFeatures xsi:type="ecore:EReference" name="initial" eType="#//Initial"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="noMatch" eType="#//NoMatch"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="noInput" eType="#//NoInput"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="match" eType="#//Match"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NoInput">
    <eStructuralFeatures xsi:type="ecore:EReference" name="audio" upperBound="-1"
        eType="#//Audio" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NoMatch">
    <eStructuralFeatures xsi:type="ecore:EReference" name="audio" upperBound="-1"
        eType="#//Audio" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Match">
    <eStructuralFeatures xsi:type="ecore:EReference" name="audio" upperBound="-1"
        eType="#//Audio" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Initial">
    <eStructuralFeatures xsi:type="ecore:EReference" name="audio" upperBound="-1"
        eType="#//Audio" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Audio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dontBargeIn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tts" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="src" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Condition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="audio" upperBound="-1"
        eType="#//Audio" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
