/**
 * generated by Xtext
 */
package com.isb.bks.ivr.voice.dsl.ui.contentassist;

import com.isb.bks.ivr.voice.dsl.ui.contentassist.AbstractVoiceDslProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class VoiceDslProposalProvider extends AbstractVoiceDslProposalProvider {
}
