/**
 * generated by Xtext
 */
package com.isb.bks.ivr.voice.dsl.ui.contentassist;

import com.google.common.collect.Sets;
import com.isb.bks.ivr.voice.dsl.ui.contentassist.AbstractVoiceDslProposalProvider;
import java.util.HashSet;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.jface.text.contentassist.ICompletionProposal;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class VoiceDslProposalProvider extends AbstractVoiceDslProposalProvider {
  public void completeConfiguration_ConfigValue(final EObject model, final Assignment assignment, final ContentAssistContext context, final ICompletionProposalAcceptor acceptor) {
    final HashSet<String> FILTERED_KEYWORDS = Sets.<String>newHashSet("maxNoInput", "maxNoMatch", "maxAttempts", "confidence", "bargein", "timeout", "interdigittimeout");
    for (final String keyword : FILTERED_KEYWORDS) {
      ICompletionProposal _createCompletionProposal = this.createCompletionProposal(keyword, keyword, null, context);
      acceptor.accept(_createCompletionProposal);
    }
    super.completeConfiguration_ConfigValue(model, assignment, context, acceptor);
  }
}
