/*
* generated by Xtext
*/
package com.isb.bks.ivr.voice.dsl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import com.isb.bks.ivr.voice.dsl.services.VoiceDslGrammarAccess;

public class VoiceDslParser extends AbstractContentAssistParser {
	
	@Inject
	private VoiceDslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected com.isb.bks.ivr.voice.dsl.ui.contentassist.antlr.internal.InternalVoiceDslParser createParser() {
		com.isb.bks.ivr.voice.dsl.ui.contentassist.antlr.internal.InternalVoiceDslParser result = new com.isb.bks.ivr.voice.dsl.ui.contentassist.antlr.internal.InternalVoiceDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getVoiceDslAccess().getAlternatives(), "rule__VoiceDsl__Alternatives");
					put(grammarAccess.getConfigValueAccess().getAlternatives_1(), "rule__ConfigValue__Alternatives_1");
					put(grammarAccess.getConfigValueValueAccess().getAlternatives(), "rule__ConfigValueValue__Alternatives");
					put(grammarAccess.getConfigValueValueAccess().getAlternatives_0_1(), "rule__ConfigValueValue__Alternatives_0_1");
					put(grammarAccess.getConfigValueValueAccess().getAlternatives_1_1(), "rule__ConfigValueValue__Alternatives_1_1");
					put(grammarAccess.getGrammarAccess().getModeAlternatives_0_0(), "rule__Grammar__ModeAlternatives_0_0");
					put(grammarAccess.getOutputValueAccess().getAlternatives(), "rule__OutputValue__Alternatives");
					put(grammarAccess.getSimpleAudioAccess().getAlternatives_2_1(), "rule__SimpleAudio__Alternatives_2_1");
					put(grammarAccess.getConditionalAudioAccess().getAlternatives(), "rule__ConditionalAudio__Alternatives");
					put(grammarAccess.getInterpretationAccess().getAlternatives(), "rule__Interpretation__Alternatives");
					put(grammarAccess.getTypeTransferAccess().getAlternatives(), "rule__TypeTransfer__Alternatives");
					put(grammarAccess.getPromptDslAccess().getGroup(), "rule__PromptDsl__Group__0");
					put(grammarAccess.getPromptDslAccess().getGroup_2(), "rule__PromptDsl__Group_2__0");
					put(grammarAccess.getMenuDslAccess().getGroup(), "rule__MenuDsl__Group__0");
					put(grammarAccess.getInputDslAccess().getGroup(), "rule__InputDsl__Group__0");
					put(grammarAccess.getRecordDslAccess().getGroup(), "rule__RecordDsl__Group__0");
					put(grammarAccess.getRecordDslAccess().getGroup_3_0(), "rule__RecordDsl__Group_3_0__0");
					put(grammarAccess.getTransferDslAccess().getGroup(), "rule__TransferDsl__Group__0");
					put(grammarAccess.getTransferDslAccess().getGroup_4_0(), "rule__TransferDsl__Group_4_0__0");
					put(grammarAccess.getTransferDslAccess().getGroup_4_1(), "rule__TransferDsl__Group_4_1__0");
					put(grammarAccess.getTransferDslAccess().getGroup_4_2(), "rule__TransferDsl__Group_4_2__0");
					put(grammarAccess.getTransferDslAccess().getGroup_4_3(), "rule__TransferDsl__Group_4_3__0");
					put(grammarAccess.getGrammarsAccess().getGroup(), "rule__Grammars__Group__0");
					put(grammarAccess.getAudiosAccess().getGroup(), "rule__Audios__Group__0");
					put(grammarAccess.getAudiosAccess().getGroup_3_0(), "rule__Audios__Group_3_0__0");
					put(grammarAccess.getAudiosAccess().getGroup_3_1(), "rule__Audios__Group_3_1__0");
					put(grammarAccess.getAudiosAccess().getGroup_3_2(), "rule__Audios__Group_3_2__0");
					put(grammarAccess.getAudiosAccess().getGroup_3_3(), "rule__Audios__Group_3_3__0");
					put(grammarAccess.getConfigurationAccess().getGroup(), "rule__Configuration__Group__0");
					put(grammarAccess.getOutputConfigurationAccess().getGroup(), "rule__OutputConfiguration__Group__0");
					put(grammarAccess.getInputConfigurationAccess().getGroup(), "rule__InputConfiguration__Group__0");
					put(grammarAccess.getRecordConfigurationAccess().getGroup(), "rule__RecordConfiguration__Group__0");
					put(grammarAccess.getTransferConfigurationAccess().getGroup(), "rule__TransferConfiguration__Group__0");
					put(grammarAccess.getConfigValueAccess().getGroup(), "rule__ConfigValue__Group__0");
					put(grammarAccess.getConfigValueValueAccess().getGroup_0(), "rule__ConfigValueValue__Group_0__0");
					put(grammarAccess.getConfigValueValueAccess().getGroup_1(), "rule__ConfigValueValue__Group_1__0");
					put(grammarAccess.getGrammarAccess().getGroup(), "rule__Grammar__Group__0");
					put(grammarAccess.getConditionAccess().getGroup(), "rule__Condition__Group__0");
					put(grammarAccess.getOutputsAccess().getGroup(), "rule__Outputs__Group__0");
					put(grammarAccess.getOutputAccess().getGroup(), "rule__Output__Group__0");
					put(grammarAccess.getOutputAccess().getGroup_3(), "rule__Output__Group_3__0");
					put(grammarAccess.getSimpleAudioAccess().getGroup(), "rule__SimpleAudio__Group__0");
					put(grammarAccess.getSimpleAudioAccess().getGroup_2(), "rule__SimpleAudio__Group_2__0");
					put(grammarAccess.getSimpleAudioAccess().getGroup_2_0(), "rule__SimpleAudio__Group_2_0__0");
					put(grammarAccess.getSimpleAudioAccess().getGroup_2_1_0(), "rule__SimpleAudio__Group_2_1_0__0");
					put(grammarAccess.getSimpleAudioAccess().getGroup_2_1_1(), "rule__SimpleAudio__Group_2_1_1__0");
					put(grammarAccess.getSimpleAudioAccess().getGroup_2_1_1_2(), "rule__SimpleAudio__Group_2_1_1_2__0");
					put(grammarAccess.getConditionalAudioAccess().getGroup_0(), "rule__ConditionalAudio__Group_0__0");
					put(grammarAccess.getFloatAccess().getGroup(), "rule__Float__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getPromptDslAccess().getNameAssignment_1(), "rule__PromptDsl__NameAssignment_1");
					put(grammarAccess.getPromptDslAccess().getConfigurationAssignment_2_0(), "rule__PromptDsl__ConfigurationAssignment_2_0");
					put(grammarAccess.getPromptDslAccess().getConditionsAssignment_2_1(), "rule__PromptDsl__ConditionsAssignment_2_1");
					put(grammarAccess.getPromptDslAccess().getAudiosAssignment_3(), "rule__PromptDsl__AudiosAssignment_3");
					put(grammarAccess.getMenuDslAccess().getNameAssignment_1(), "rule__MenuDsl__NameAssignment_1");
					put(grammarAccess.getMenuDslAccess().getConfigurationAssignment_2(), "rule__MenuDsl__ConfigurationAssignment_2");
					put(grammarAccess.getMenuDslAccess().getGrammarsAssignment_3_0(), "rule__MenuDsl__GrammarsAssignment_3_0");
					put(grammarAccess.getMenuDslAccess().getConditionsAssignment_3_1(), "rule__MenuDsl__ConditionsAssignment_3_1");
					put(grammarAccess.getMenuDslAccess().getAudiosAssignment_4(), "rule__MenuDsl__AudiosAssignment_4");
					put(grammarAccess.getMenuDslAccess().getOutputsAssignment_5(), "rule__MenuDsl__OutputsAssignment_5");
					put(grammarAccess.getInputDslAccess().getNameAssignment_1(), "rule__InputDsl__NameAssignment_1");
					put(grammarAccess.getInputDslAccess().getConfigurationAssignment_2(), "rule__InputDsl__ConfigurationAssignment_2");
					put(grammarAccess.getInputDslAccess().getGrammarsAssignment_3_0(), "rule__InputDsl__GrammarsAssignment_3_0");
					put(grammarAccess.getInputDslAccess().getConditionsAssignment_3_1(), "rule__InputDsl__ConditionsAssignment_3_1");
					put(grammarAccess.getInputDslAccess().getAudiosAssignment_4(), "rule__InputDsl__AudiosAssignment_4");
					put(grammarAccess.getRecordDslAccess().getNameAssignment_1(), "rule__RecordDsl__NameAssignment_1");
					put(grammarAccess.getRecordDslAccess().getFileNameAssignment_3_0_1(), "rule__RecordDsl__FileNameAssignment_3_0_1");
					put(grammarAccess.getRecordDslAccess().getConfigurationAssignment_3_1(), "rule__RecordDsl__ConfigurationAssignment_3_1");
					put(grammarAccess.getRecordDslAccess().getConditionsAssignment_5(), "rule__RecordDsl__ConditionsAssignment_5");
					put(grammarAccess.getRecordDslAccess().getAudiosAssignment_6(), "rule__RecordDsl__AudiosAssignment_6");
					put(grammarAccess.getTransferDslAccess().getTypeTransferAssignment_1(), "rule__TransferDsl__TypeTransferAssignment_1");
					put(grammarAccess.getTransferDslAccess().getNameAssignment_2(), "rule__TransferDsl__NameAssignment_2");
					put(grammarAccess.getTransferDslAccess().getDestinationAssignment_4_0_1(), "rule__TransferDsl__DestinationAssignment_4_0_1");
					put(grammarAccess.getTransferDslAccess().getAudioTransferAssignment_4_1_1(), "rule__TransferDsl__AudioTransferAssignment_4_1_1");
					put(grammarAccess.getTransferDslAccess().getMaxTimeAssignment_4_2_1(), "rule__TransferDsl__MaxTimeAssignment_4_2_1");
					put(grammarAccess.getTransferDslAccess().getTimeoutAssignment_4_3_1(), "rule__TransferDsl__TimeoutAssignment_4_3_1");
					put(grammarAccess.getTransferDslAccess().getConfigurationAssignment_4_4(), "rule__TransferDsl__ConfigurationAssignment_4_4");
					put(grammarAccess.getTransferDslAccess().getConditionsAssignment_6(), "rule__TransferDsl__ConditionsAssignment_6");
					put(grammarAccess.getTransferDslAccess().getAudiosAssignment_7(), "rule__TransferDsl__AudiosAssignment_7");
					put(grammarAccess.getGrammarsAccess().getGrammaticsAssignment_3(), "rule__Grammars__GrammaticsAssignment_3");
					put(grammarAccess.getAudiosAccess().getMainAudiosAssignment_3_0_2(), "rule__Audios__MainAudiosAssignment_3_0_2");
					put(grammarAccess.getAudiosAccess().getMatchAudiosAssignment_3_1_2(), "rule__Audios__MatchAudiosAssignment_3_1_2");
					put(grammarAccess.getAudiosAccess().getNoMatchAudiosAssignment_3_2_2(), "rule__Audios__NoMatchAudiosAssignment_3_2_2");
					put(grammarAccess.getAudiosAccess().getNoInputAudiosAssignment_3_3_2(), "rule__Audios__NoInputAudiosAssignment_3_3_2");
					put(grammarAccess.getConfigurationAccess().getConfigValueAssignment_2(), "rule__Configuration__ConfigValueAssignment_2");
					put(grammarAccess.getOutputConfigurationAccess().getConfigValueAssignment_2(), "rule__OutputConfiguration__ConfigValueAssignment_2");
					put(grammarAccess.getInputConfigurationAccess().getConfigValueAssignment_2(), "rule__InputConfiguration__ConfigValueAssignment_2");
					put(grammarAccess.getRecordConfigurationAccess().getConfigValueAssignment_1(), "rule__RecordConfiguration__ConfigValueAssignment_1");
					put(grammarAccess.getTransferConfigurationAccess().getConfigValueAssignment_1(), "rule__TransferConfiguration__ConfigValueAssignment_1");
					put(grammarAccess.getConfigValueAccess().getNameAssignment_0(), "rule__ConfigValue__NameAssignment_0");
					put(grammarAccess.getConfigValueAccess().getValueAssignment_1_0(), "rule__ConfigValue__ValueAssignment_1_0");
					put(grammarAccess.getConfigValueAccess().getValueAssignment_1_1(), "rule__ConfigValue__ValueAssignment_1_1");
					put(grammarAccess.getGrammarAccess().getModeAssignment_0(), "rule__Grammar__ModeAssignment_0");
					put(grammarAccess.getGrammarAccess().getExprAssignment_1(), "rule__Grammar__ExprAssignment_1");
					put(grammarAccess.getGrammarAccess().getSrcAssignment_2(), "rule__Grammar__SrcAssignment_2");
					put(grammarAccess.getConditionAccess().getNameAssignment_2(), "rule__Condition__NameAssignment_2");
					put(grammarAccess.getConditionAccess().getConditionAssignment_3(), "rule__Condition__ConditionAssignment_3");
					put(grammarAccess.getOutputsAccess().getOutputAssignment_2(), "rule__Outputs__OutputAssignment_2");
					put(grammarAccess.getOutputAccess().getNameAssignment_0(), "rule__Output__NameAssignment_0");
					put(grammarAccess.getOutputAccess().getOutputValueAssignment_2(), "rule__Output__OutputValueAssignment_2");
					put(grammarAccess.getOutputAccess().getOutputValueAssignment_3_1(), "rule__Output__OutputValueAssignment_3_1");
					put(grammarAccess.getOutputValueAccess().getValueAssignment_0(), "rule__OutputValue__ValueAssignment_0");
					put(grammarAccess.getOutputValueAccess().getValueAssignment_1(), "rule__OutputValue__ValueAssignment_1");
					put(grammarAccess.getSimpleAudioAccess().getSrcAssignment_2_0_1(), "rule__SimpleAudio__SrcAssignment_2_0_1");
					put(grammarAccess.getSimpleAudioAccess().getTtsAssignment_2_1_0_1(), "rule__SimpleAudio__TtsAssignment_2_1_0_1");
					put(grammarAccess.getSimpleAudioAccess().getInterpretationAssignment_2_1_1_1(), "rule__SimpleAudio__InterpretationAssignment_2_1_1_1");
					put(grammarAccess.getSimpleAudioAccess().getFormatAssignment_2_1_1_2_1(), "rule__SimpleAudio__FormatAssignment_2_1_1_2_1");
					put(grammarAccess.getSimpleAudioAccess().getTtsAssignment_2_1_1_3(), "rule__SimpleAudio__TtsAssignment_2_1_1_3");
					put(grammarAccess.getConditionalAudioAccess().getConditAssignment_0_3(), "rule__ConditionalAudio__ConditAssignment_0_3");
					put(grammarAccess.getConditionalAudioAccess().getSimpleAudiosAssignment_0_6(), "rule__ConditionalAudio__SimpleAudiosAssignment_0_6");
					put(grammarAccess.getMenuDslAccess().getUnorderedGroup_3(), "rule__MenuDsl__UnorderedGroup_3");
					put(grammarAccess.getInputDslAccess().getUnorderedGroup_3(), "rule__InputDsl__UnorderedGroup_3");
					put(grammarAccess.getRecordDslAccess().getUnorderedGroup_3(), "rule__RecordDsl__UnorderedGroup_3");
					put(grammarAccess.getTransferDslAccess().getUnorderedGroup_4(), "rule__TransferDsl__UnorderedGroup_4");
					put(grammarAccess.getAudiosAccess().getUnorderedGroup_3(), "rule__Audios__UnorderedGroup_3");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			com.isb.bks.ivr.voice.dsl.ui.contentassist.antlr.internal.InternalVoiceDslParser typedParser = (com.isb.bks.ivr.voice.dsl.ui.contentassist.antlr.internal.InternalVoiceDslParser) parser;
			typedParser.entryRuleVoiceDsl();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public VoiceDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(VoiceDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
