/*
* generated by Xtext
*/
package com.isb.bks.ivr.voice.dsl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import com.isb.bks.ivr.voice.dsl.services.VoiceDslGrammarAccess;

public class VoiceDslParser extends AbstractContentAssistParser {
	
	@Inject
	private VoiceDslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected com.isb.bks.ivr.voice.dsl.ui.contentassist.antlr.internal.InternalVoiceDslParser createParser() {
		com.isb.bks.ivr.voice.dsl.ui.contentassist.antlr.internal.InternalVoiceDslParser result = new com.isb.bks.ivr.voice.dsl.ui.contentassist.antlr.internal.InternalVoiceDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getVoiceDslAccess().getAlternatives(), "rule__VoiceDsl__Alternatives");
					put(grammarAccess.getTransferDslAccess().getAlternatives_0(), "rule__TransferDsl__Alternatives_0");
					put(grammarAccess.getConfigValueValueAccess().getAlternatives(), "rule__ConfigValueValue__Alternatives");
					put(grammarAccess.getConfigValueValueAccess().getAlternatives_0_1(), "rule__ConfigValueValue__Alternatives_0_1");
					put(grammarAccess.getGrammarAccess().getModeAlternatives_0_0(), "rule__Grammar__ModeAlternatives_0_0");
					put(grammarAccess.getOutputValueAccess().getAlternatives(), "rule__OutputValue__Alternatives");
					put(grammarAccess.getSimpleAudioAccess().getAlternatives_2_1(), "rule__SimpleAudio__Alternatives_2_1");
					put(grammarAccess.getConditionalAudioAccess().getAlternatives(), "rule__ConditionalAudio__Alternatives");
					put(grammarAccess.getInterpretationAccess().getAlternatives(), "rule__Interpretation__Alternatives");
					put(grammarAccess.getTypeTransferAccess().getAlternatives(), "rule__TypeTransfer__Alternatives");
					put(grammarAccess.getPromptDslAccess().getGroup(), "rule__PromptDsl__Group__0");
					put(grammarAccess.getMenuDslAccess().getGroup(), "rule__MenuDsl__Group__0");
					put(grammarAccess.getInputDslAccess().getGroup(), "rule__InputDsl__Group__0");
					put(grammarAccess.getRecordDslAccess().getGroup(), "rule__RecordDsl__Group__0");
					put(grammarAccess.getTransferDslAccess().getGroup(), "rule__TransferDsl__Group__0");
					put(grammarAccess.getTransferDslAccess().getGroup_0_0(), "rule__TransferDsl__Group_0_0__0");
					put(grammarAccess.getTransferDslAccess().getGroup_0_1(), "rule__TransferDsl__Group_0_1__0");
					put(grammarAccess.getTransferDslAccess().getGroup_0_2(), "rule__TransferDsl__Group_0_2__0");
					put(grammarAccess.getTransferDslAccess().getGroup_1_0(), "rule__TransferDsl__Group_1_0__0");
					put(grammarAccess.getTransferDslAccess().getGroup_1_1(), "rule__TransferDsl__Group_1_1__0");
					put(grammarAccess.getTransferDslAccess().getGroup_1_2(), "rule__TransferDsl__Group_1_2__0");
					put(grammarAccess.getTransferDslAccess().getGroup_1_3(), "rule__TransferDsl__Group_1_3__0");
					put(grammarAccess.getGrammarsAccess().getGroup(), "rule__Grammars__Group__0");
					put(grammarAccess.getAudiosAccess().getGroup_0(), "rule__Audios__Group_0__0");
					put(grammarAccess.getAudiosAccess().getGroup_0_2(), "rule__Audios__Group_0_2__0");
					put(grammarAccess.getAudiosAccess().getGroup_1(), "rule__Audios__Group_1__0");
					put(grammarAccess.getAudiosAccess().getGroup_2(), "rule__Audios__Group_2__0");
					put(grammarAccess.getAudiosAccess().getGroup_3(), "rule__Audios__Group_3__0");
					put(grammarAccess.getConfigurationAccess().getGroup(), "rule__Configuration__Group__0");
					put(grammarAccess.getConfigValueAccess().getGroup(), "rule__ConfigValue__Group__0");
					put(grammarAccess.getConfigValueValueAccess().getGroup_0(), "rule__ConfigValueValue__Group_0__0");
					put(grammarAccess.getGrammarAccess().getGroup(), "rule__Grammar__Group__0");
					put(grammarAccess.getConditionAccess().getGroup(), "rule__Condition__Group__0");
					put(grammarAccess.getOutputsAccess().getGroup(), "rule__Outputs__Group__0");
					put(grammarAccess.getOutputAccess().getGroup(), "rule__Output__Group__0");
					put(grammarAccess.getOutputAccess().getGroup_3(), "rule__Output__Group_3__0");
					put(grammarAccess.getSimpleAudioAccess().getGroup(), "rule__SimpleAudio__Group__0");
					put(grammarAccess.getSimpleAudioAccess().getGroup_2(), "rule__SimpleAudio__Group_2__0");
					put(grammarAccess.getSimpleAudioAccess().getGroup_2_0(), "rule__SimpleAudio__Group_2_0__0");
					put(grammarAccess.getSimpleAudioAccess().getGroup_2_1_0(), "rule__SimpleAudio__Group_2_1_0__0");
					put(grammarAccess.getSimpleAudioAccess().getGroup_2_1_1(), "rule__SimpleAudio__Group_2_1_1__0");
					put(grammarAccess.getSimpleAudioAccess().getGroup_2_1_1_2(), "rule__SimpleAudio__Group_2_1_1_2__0");
					put(grammarAccess.getConditionalAudioAccess().getGroup_0(), "rule__ConditionalAudio__Group_0__0");
					put(grammarAccess.getPromptDslAccess().getNameAssignment_1(), "rule__PromptDsl__NameAssignment_1");
					put(grammarAccess.getPromptDslAccess().getConfigurationAssignment_2_0(), "rule__PromptDsl__ConfigurationAssignment_2_0");
					put(grammarAccess.getPromptDslAccess().getConditionsAssignment_2_1(), "rule__PromptDsl__ConditionsAssignment_2_1");
					put(grammarAccess.getPromptDslAccess().getAudiosAssignment_3(), "rule__PromptDsl__AudiosAssignment_3");
					put(grammarAccess.getMenuDslAccess().getNameAssignment_1(), "rule__MenuDsl__NameAssignment_1");
					put(grammarAccess.getMenuDslAccess().getConfigurationAssignment_2_0(), "rule__MenuDsl__ConfigurationAssignment_2_0");
					put(grammarAccess.getMenuDslAccess().getGrammarsAssignment_2_1(), "rule__MenuDsl__GrammarsAssignment_2_1");
					put(grammarAccess.getMenuDslAccess().getConditionsAssignment_2_2(), "rule__MenuDsl__ConditionsAssignment_2_2");
					put(grammarAccess.getMenuDslAccess().getAudiosAssignment_3(), "rule__MenuDsl__AudiosAssignment_3");
					put(grammarAccess.getMenuDslAccess().getOutputsAssignment_4(), "rule__MenuDsl__OutputsAssignment_4");
					put(grammarAccess.getInputDslAccess().getNameAssignment_1(), "rule__InputDsl__NameAssignment_1");
					put(grammarAccess.getInputDslAccess().getConfigurationAssignment_2_0(), "rule__InputDsl__ConfigurationAssignment_2_0");
					put(grammarAccess.getInputDslAccess().getGrammarsAssignment_2_1(), "rule__InputDsl__GrammarsAssignment_2_1");
					put(grammarAccess.getInputDslAccess().getConditionsAssignment_2_2(), "rule__InputDsl__ConditionsAssignment_2_2");
					put(grammarAccess.getInputDslAccess().getAudiosAssignment_3(), "rule__InputDsl__AudiosAssignment_3");
					put(grammarAccess.getRecordDslAccess().getNameAssignment_1(), "rule__RecordDsl__NameAssignment_1");
					put(grammarAccess.getRecordDslAccess().getFileNameAssignment_3(), "rule__RecordDsl__FileNameAssignment_3");
					put(grammarAccess.getRecordDslAccess().getConfigurationAssignment_4_0(), "rule__RecordDsl__ConfigurationAssignment_4_0");
					put(grammarAccess.getRecordDslAccess().getConditionsAssignment_4_1(), "rule__RecordDsl__ConditionsAssignment_4_1");
					put(grammarAccess.getRecordDslAccess().getAudiosAssignment_5(), "rule__RecordDsl__AudiosAssignment_5");
					put(grammarAccess.getTransferDslAccess().getNameAssignment_0_0_1(), "rule__TransferDsl__NameAssignment_0_0_1");
					put(grammarAccess.getTransferDslAccess().getNameAssignment_0_1_1(), "rule__TransferDsl__NameAssignment_0_1_1");
					put(grammarAccess.getTransferDslAccess().getNameAssignment_0_2_1(), "rule__TransferDsl__NameAssignment_0_2_1");
					put(grammarAccess.getTransferDslAccess().getDestinationAssignment_1_0_1(), "rule__TransferDsl__DestinationAssignment_1_0_1");
					put(grammarAccess.getTransferDslAccess().getAudioTransferAssignment_1_1_1(), "rule__TransferDsl__AudioTransferAssignment_1_1_1");
					put(grammarAccess.getTransferDslAccess().getMaxTimeAssignment_1_2_1(), "rule__TransferDsl__MaxTimeAssignment_1_2_1");
					put(grammarAccess.getTransferDslAccess().getTimeoutAssignment_1_3_1(), "rule__TransferDsl__TimeoutAssignment_1_3_1");
					put(grammarAccess.getTransferDslAccess().getConditionsAssignment_2(), "rule__TransferDsl__ConditionsAssignment_2");
					put(grammarAccess.getTransferDslAccess().getAudiosAssignment_3(), "rule__TransferDsl__AudiosAssignment_3");
					put(grammarAccess.getGrammarsAccess().getGrammaticsAssignment_3(), "rule__Grammars__GrammaticsAssignment_3");
					put(grammarAccess.getAudiosAccess().getMainAudiosAssignment_0_2_2(), "rule__Audios__MainAudiosAssignment_0_2_2");
					put(grammarAccess.getAudiosAccess().getMatchAudiosAssignment_1_2(), "rule__Audios__MatchAudiosAssignment_1_2");
					put(grammarAccess.getAudiosAccess().getNoMatchAudiosAssignment_2_2(), "rule__Audios__NoMatchAudiosAssignment_2_2");
					put(grammarAccess.getAudiosAccess().getNoInputAudiosAssignment_3_2(), "rule__Audios__NoInputAudiosAssignment_3_2");
					put(grammarAccess.getConfigurationAccess().getConfigValueAssignment_2(), "rule__Configuration__ConfigValueAssignment_2");
					put(grammarAccess.getConfigValueAccess().getNameAssignment_0(), "rule__ConfigValue__NameAssignment_0");
					put(grammarAccess.getConfigValueAccess().getValueAssignment_1(), "rule__ConfigValue__ValueAssignment_1");
					put(grammarAccess.getGrammarAccess().getModeAssignment_0(), "rule__Grammar__ModeAssignment_0");
					put(grammarAccess.getGrammarAccess().getExprAssignment_1(), "rule__Grammar__ExprAssignment_1");
					put(grammarAccess.getGrammarAccess().getSrcAssignment_2(), "rule__Grammar__SrcAssignment_2");
					put(grammarAccess.getConditionAccess().getNameAssignment_2(), "rule__Condition__NameAssignment_2");
					put(grammarAccess.getConditionAccess().getConditionAssignment_3(), "rule__Condition__ConditionAssignment_3");
					put(grammarAccess.getOutputsAccess().getOutputAssignment_2(), "rule__Outputs__OutputAssignment_2");
					put(grammarAccess.getOutputAccess().getNameAssignment_0(), "rule__Output__NameAssignment_0");
					put(grammarAccess.getOutputAccess().getOutputValueAssignment_2(), "rule__Output__OutputValueAssignment_2");
					put(grammarAccess.getOutputAccess().getOutputValueAssignment_3_1(), "rule__Output__OutputValueAssignment_3_1");
					put(grammarAccess.getOutputValueAccess().getValueAssignment_0(), "rule__OutputValue__ValueAssignment_0");
					put(grammarAccess.getOutputValueAccess().getValueAssignment_1(), "rule__OutputValue__ValueAssignment_1");
					put(grammarAccess.getSimpleAudioAccess().getSrcAssignment_2_0_1(), "rule__SimpleAudio__SrcAssignment_2_0_1");
					put(grammarAccess.getSimpleAudioAccess().getTtsAssignment_2_1_0_1(), "rule__SimpleAudio__TtsAssignment_2_1_0_1");
					put(grammarAccess.getSimpleAudioAccess().getInterpretationAssignment_2_1_1_1(), "rule__SimpleAudio__InterpretationAssignment_2_1_1_1");
					put(grammarAccess.getSimpleAudioAccess().getFormatAssignment_2_1_1_2_1(), "rule__SimpleAudio__FormatAssignment_2_1_1_2_1");
					put(grammarAccess.getSimpleAudioAccess().getTtsAssignment_2_1_1_3(), "rule__SimpleAudio__TtsAssignment_2_1_1_3");
					put(grammarAccess.getConditionalAudioAccess().getConditAssignment_0_3(), "rule__ConditionalAudio__ConditAssignment_0_3");
					put(grammarAccess.getConditionalAudioAccess().getSimpleAudiosAssignment_0_6(), "rule__ConditionalAudio__SimpleAudiosAssignment_0_6");
					put(grammarAccess.getPromptDslAccess().getUnorderedGroup_2(), "rule__PromptDsl__UnorderedGroup_2");
					put(grammarAccess.getMenuDslAccess().getUnorderedGroup_2(), "rule__MenuDsl__UnorderedGroup_2");
					put(grammarAccess.getInputDslAccess().getUnorderedGroup_2(), "rule__InputDsl__UnorderedGroup_2");
					put(grammarAccess.getRecordDslAccess().getUnorderedGroup_4(), "rule__RecordDsl__UnorderedGroup_4");
					put(grammarAccess.getTransferDslAccess().getUnorderedGroup_1(), "rule__TransferDsl__UnorderedGroup_1");
					put(grammarAccess.getAudiosAccess().getUnorderedGroup(), "rule__Audios__UnorderedGroup");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			com.isb.bks.ivr.voice.dsl.ui.contentassist.antlr.internal.InternalVoiceDslParser typedParser = (com.isb.bks.ivr.voice.dsl.ui.contentassist.antlr.internal.InternalVoiceDslParser) parser;
			typedParser.entryRuleVoiceDsl();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public VoiceDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(VoiceDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
