
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicesSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicesSoap {


    /**
     * 
     * @param connID
     * @param nss
     * @param callID
     * @return
     *     returns org.tempuri.JWServiceMerchListPRResponse2
     */
    @WebMethod(operationName = "JWServiceMerchListPR", action = "http://tempuri.org/JWServiceMerchListPR")
    @WebResult(name = "JWServiceMerchListPRResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "JWServiceMerchListPR", targetNamespace = "http://tempuri.org/", className = "org.tempuri.JWServiceMerchListPR")
    @ResponseWrapper(localName = "JWServiceMerchListPRResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.JWServiceMerchListPRResponse")
    public JWServiceMerchListPRResponse2 jwServiceMerchListPR(
        @WebParam(name = "connID", targetNamespace = "http://tempuri.org/")
        String connID,
        @WebParam(name = "callID", targetNamespace = "http://tempuri.org/")
        String callID,
        @WebParam(name = "NSS", targetNamespace = "http://tempuri.org/")
        String nss);

    /**
     * 
     * @param connID
     * @param customerId
     * @param merchantId
     * @param callID
     * @return
     *     returns org.tempuri.JWServiceCtasMerchPRResponse2
     */
    @WebMethod(operationName = "JWServiceCtasMerchPR", action = "http://tempuri.org/JWServiceCtasMerchPR")
    @WebResult(name = "JWServiceCtasMerchPRResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "JWServiceCtasMerchPR", targetNamespace = "http://tempuri.org/", className = "org.tempuri.JWServiceCtasMerchPR")
    @ResponseWrapper(localName = "JWServiceCtasMerchPRResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.JWServiceCtasMerchPRResponse")
    public JWServiceCtasMerchPRResponse2 jwServiceCtasMerchPR(
        @WebParam(name = "connID", targetNamespace = "http://tempuri.org/")
        String connID,
        @WebParam(name = "callID", targetNamespace = "http://tempuri.org/")
        String callID,
        @WebParam(name = "customerId", targetNamespace = "http://tempuri.org/")
        String customerId,
        @WebParam(name = "merchantId", targetNamespace = "http://tempuri.org/")
        String merchantId);

    /**
     * 
     * @param connID
     * @param customerId
     * @param idMerchantCta
     * @param callID
     * @return
     *     returns org.tempuri.JWServiceCtasCustPRResponse2
     */
    @WebMethod(operationName = "JWServiceCtasCustPR", action = "http://tempuri.org/JWServiceCtasCustPR")
    @WebResult(name = "JWServiceCtasCustPRResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "JWServiceCtasCustPR", targetNamespace = "http://tempuri.org/", className = "org.tempuri.JWServiceCtasCustPR")
    @ResponseWrapper(localName = "JWServiceCtasCustPRResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.JWServiceCtasCustPRResponse")
    public JWServiceCtasCustPRResponse2 jwServiceCtasCustPR(
        @WebParam(name = "connID", targetNamespace = "http://tempuri.org/")
        String connID,
        @WebParam(name = "callID", targetNamespace = "http://tempuri.org/")
        String callID,
        @WebParam(name = "customerId", targetNamespace = "http://tempuri.org/")
        String customerId,
        @WebParam(name = "idMerchantCta", targetNamespace = "http://tempuri.org/")
        String idMerchantCta);

    /**
     * 
     * @param connID
     * @param numCuenta
     * @param customerId
     * @param idMerchantCta
     * @param fechProcPay
     * @param merchantId
     * @param callID
     * @param montoPay
     * @return
     *     returns org.tempuri.JWServiceMerchantPayResponse2
     */
    @WebMethod(operationName = "JWServiceMerchantPay", action = "http://tempuri.org/JWServiceMerchantPay")
    @WebResult(name = "JWServiceMerchantPayResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "JWServiceMerchantPay", targetNamespace = "http://tempuri.org/", className = "org.tempuri.JWServiceMerchantPay")
    @ResponseWrapper(localName = "JWServiceMerchantPayResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.JWServiceMerchantPayResponse")
    public JWServiceMerchantPayResponse2 jwServiceMerchantPay(
        @WebParam(name = "connID", targetNamespace = "http://tempuri.org/")
        String connID,
        @WebParam(name = "callID", targetNamespace = "http://tempuri.org/")
        String callID,
        @WebParam(name = "customerId", targetNamespace = "http://tempuri.org/")
        String customerId,
        @WebParam(name = "numCuenta", targetNamespace = "http://tempuri.org/")
        String numCuenta,
        @WebParam(name = "merchantId", targetNamespace = "http://tempuri.org/")
        String merchantId,
        @WebParam(name = "idMerchantCta", targetNamespace = "http://tempuri.org/")
        String idMerchantCta,
        @WebParam(name = "montoPay", targetNamespace = "http://tempuri.org/")
        String montoPay,
        @WebParam(name = "FechProcPay", targetNamespace = "http://tempuri.org/")
        String fechProcPay);

    /**
     * 
     * @param connID
     * @param customerId
     * @param nss
     * @param callID
     * @return
     *     returns org.tempuri.JWServiceUlt5PagosProcPRResponse2
     */
    @WebMethod(operationName = "JWServiceUlt5PagosProcPR", action = "http://tempuri.org/JWServiceUlt5PagosProcPR")
    @WebResult(name = "JWServiceUlt5PagosProcPRResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "JWServiceUlt5PagosProcPR", targetNamespace = "http://tempuri.org/", className = "org.tempuri.JWServiceUlt5PagosProcPR")
    @ResponseWrapper(localName = "JWServiceUlt5PagosProcPRResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.JWServiceUlt5PagosProcPRResponse")
    public JWServiceUlt5PagosProcPRResponse2 jwServiceUlt5PagosProcPR(
        @WebParam(name = "connID", targetNamespace = "http://tempuri.org/")
        String connID,
        @WebParam(name = "callID", targetNamespace = "http://tempuri.org/")
        String callID,
        @WebParam(name = "NSS", targetNamespace = "http://tempuri.org/")
        String nss,
        @WebParam(name = "customerId", targetNamespace = "http://tempuri.org/")
        String customerId);

    /**
     * 
     * @param connID
     * @param customerId
     * @param nss
     * @param callID
     * @return
     *     returns org.tempuri.JWServicePagosPendPRResponse2
     */
    @WebMethod(operationName = "JWServicePagosPendPR", action = "http://tempuri.org/JWServicePagosPendPR")
    @WebResult(name = "JWServicePagosPendPRResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "JWServicePagosPendPR", targetNamespace = "http://tempuri.org/", className = "org.tempuri.JWServicePagosPendPR")
    @ResponseWrapper(localName = "JWServicePagosPendPRResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.JWServicePagosPendPRResponse")
    public JWServicePagosPendPRResponse2 jwServicePagosPendPR(
        @WebParam(name = "connID", targetNamespace = "http://tempuri.org/")
        String connID,
        @WebParam(name = "callID", targetNamespace = "http://tempuri.org/")
        String callID,
        @WebParam(name = "NSS", targetNamespace = "http://tempuri.org/")
        String nss,
        @WebParam(name = "customerId", targetNamespace = "http://tempuri.org/")
        String customerId);

}
