<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="operations" nsURI="http://jvoice.vectorsf.com/operations/1.0"
    nsPrefix="operations">
  <eClassifiers xsi:type="ecore:EClass" name="State" abstract="true" eSuperTypes="../../com.vectorsf.jvoice.base.model/model/Base.ecore#//NamedElement">
    <eOperations name="getEvents" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return new org.eclipse.emf.common.util.BasicEList&lt;String>();"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingTransitions" upperBound="-1"
        eType="#//Transition" eOpposite="#//Transition/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingTransitions" upperBound="-1"
        eType="#//Transition" eOpposite="#//Transition/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="notes" eType="#//Note"
        eOpposite="#//Note/referencedStates"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fireableEvents" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="../../com.vectorsf.jvoice.base.model/model/Base.ecore#//JVElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//State" eOpposite="#//State/outgoingTransitions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//State" eOpposite="#//State/incomingTransitions"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eventName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Flow" eSuperTypes="../../com.vectorsf.jvoice.base.model/model/Base.ecore#//JVBean">
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        eType="#//State" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="notes" upperBound="-1"
        eType="#//Note" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beans" upperBound="-1"
        eType="#//ComponentBean" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameters" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitialState" eSuperTypes="#//State"/>
  <eClassifiers xsi:type="ecore:EClass" name="FinalState" eSuperTypes="#//State">
    <eOperations name="getEvents" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return new org.eclipse.emf.common.util.BasicEList&lt;String>();"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnExpression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SwitchState" eSuperTypes="#//State">
    <eOperations name="getCase" eType="#//Case">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="for (Case switchCase: getCase()) {&#xD;&#xA;&#x9;if (switchCase.getEventName().equals(name)) {&#xD;&#xA;&#x9;&#x9;return switchCase;&#xD;&#xA;&#x9;}&#xD;&#xA;}&#xD;&#xA;&#x9;&#x9;&#xD;&#xA;return null;"/>
      </eAnnotations>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getEvents" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="EList&lt;String> ret = new &lt;%org.eclipse.emf.common.util.BasicEList%>&lt;String>();&#xA;&#xA;for (Case current: getCase()) {&#xA;&#x9;ret.add(current.getEventName());&#xA;}&#xA;&#xA;return ret;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="case" upperBound="-1" eType="#//Case"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Case">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eventName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallState" eSuperTypes="#//ParameterizedState">
    <eOperations name="getEvents" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="EList&lt;String> ret = new &lt;%org.eclipse.emf.common.util.BasicEList%>&lt;String>();&#xA;&#xA;ret.add(&quot;ok&quot;);&#xA;ret.add(&quot;error&quot;);&#xA;&#xA;&#xA;return ret;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="methodName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bean" eType="#//ComponentBean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedBean" eType="#//ComponentBean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallFlowState" eSuperTypes="#//ParameterizedState">
    <eOperations name="getEvents" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="EList&lt;String> list = new &lt;%org.eclipse.emf.common.util.BasicEList%>&lt;String>();&#xD;&#xA;&#xD;&#xA;for(State state: getSubflow().getStates()) {&#xD;&#xA;&#x9;if (state instanceof &lt;%com.vectorsf.jvoice.model.operations.FinalState%> &amp;&amp; !((FinalState)state).isFinal()) {&#xD;&#xA;&#x9;&#x9;list.add(state.getName());&#xD;&#xA;&#x9;}&#xD;&#xA;}&#xD;&#xA;return list;&#xD;&#xD;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subflow" eType="#//Flow"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PromptState" eSuperTypes="#//LocutionState">
    <eOperations name="getEvents" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="EList&lt;String> ret = new &lt;%org.eclipse.emf.common.util.BasicEList%>&lt;String>();&#xA;&#xA;ret.add(&quot;ok&quot;);&#xA;ret.add(&quot;hangup&quot;);&#xA;&#xA;return ret;"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputState" eSuperTypes="#//LocutionState">
    <eOperations name="getEvents" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="EList&lt;String> ret = new &lt;%org.eclipse.emf.common.util.BasicEList%>&lt;String>();&#xA;&#xA;ret.add(&quot;ok&quot;);&#xA;ret.add(&quot;error&quot;);&#xA;ret.add(&quot;noresource&quot;);&#xA;ret.add(&quot;maxattempts&quot;);&#xA;ret.add(&quot;maxnoinput&quot;);&#xA;ret.add(&quot;maxnomatch&quot;);&#xA;ret.add(&quot;hangup&quot;);&#xA;&#xA;return ret;"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MenuState" eSuperTypes="#//LocutionState">
    <eOperations name="getEvents" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="EList&lt;String> ret = new &lt;%org.eclipse.emf.common.util.BasicEList%>&lt;String>();&#xD;&#xA;&#xD;&#xA;ret.add(&quot;error&quot;);&#xD;&#xA;ret.add(&quot;noresource&quot;);&#xD;&#xA;ret.add(&quot;maxattempts&quot;);&#xD;&#xA;ret.add(&quot;maxnoinput&quot;);&#xD;&#xA;ret.add(&quot;maxnomatch&quot;);&#xD;&#xA;ret.add(&quot;hangup&quot;);&#xD;&#xA;&#xD;&#xA;return ret;"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocutionState" abstract="true" eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="locution" eType="ecore:EClass ../../com.vectorsf.jvoice.prompt.model/model/VoiceDsl.ecore#//VoiceDsl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransferState" eSuperTypes="#//LocutionState">
    <eOperations name="getEvents" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="EList&lt;String> ret = new &lt;%org.eclipse.emf.common.util.BasicEList%>&lt;String>();&#xA;&#xA;&lt;%com.vectorsf.jvoice.prompt.model.voiceDsl.TypeTransfer%> type = ((&lt;%com.vectorsf.jvoice.prompt.model.voiceDsl.TransferDsl%>) getLocution()).getTypeTransfer();&#xA;&#xA;ret.add(&quot;ok&quot;);&#xA;ret.add(&quot;error&quot;);&#xA;ret.add(&quot;noresource&quot;);&#xA;ret.add(&quot;connectionerror&quot;);&#xA;ret.add(&quot;unknown&quot;);&#xA;ret.add(&quot;near_end_disconnect&quot;);&#xA;&#xA;if (type==TypeTransfer.CONSULTATION || type==TypeTransfer.BRIDGE) {&#xA;&#x9;ret.add(&quot;noanswer&quot;);&#xA;&#x9;ret.add(&quot;busy&quot;);&#xA;&#x9;ret.add(&quot;network_busy&quot;);&#xA;}&#xA;&#xA;if (type==TypeTransfer.BRIDGE) {&#xA;&#x9;ret.add(&quot;maxtime_disconnect&quot;);&#xA;&#x9;ret.add(&quot;network_disconnect&quot;);&#xA;&#x9;ret.add(&quot;far_end_disconnect&quot;);&#xA;}&#xA;&#xA;ret.add(&quot;hangup&quot;);&#xA;&#xA;return ret;"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RecordState" eSuperTypes="#//LocutionState">
    <eOperations name="getEvents" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="EList&lt;String> ret = new &lt;%org.eclipse.emf.common.util.BasicEList%>&lt;String>();&#xA;&#xA;ret.add(&quot;ok&quot;);&#xA;ret.add(&quot;error&quot;);&#xA;ret.add(&quot;noresource&quot;);&#xA;ret.add(&quot;recordunsupported&quot;);&#xA;ret.add(&quot;hangup&quot;);&#xA;&#xA;return ret;"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Note" eSuperTypes="../../com.vectorsf.jvoice.base.model/model/Base.ecore#//JVElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedStates" upperBound="-1"
        eType="#//State" eOpposite="#//State/notes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomState" eSuperTypes="#//State">
    <eOperations name="getEvents" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="EList&lt;String> ret = new &lt;%org.eclipse.emf.common.util.BasicEList%>&lt;String>();&#xD;&#xA;&#xD;&#xA;ret.add(&quot;ok&quot;);&#xD;&#xA;&#xD;&#xA;return ret;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bindingBean" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentBean" eSuperTypes="../../com.vectorsf.jvoice.base.model/model/Base.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fqdn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameBean" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prototype" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterizedState" abstract="true"
      eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameters" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
