<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="operations" nsURI="http://jvoice.vectorsf.com/operations/1.0"
    nsPrefix="operations">
  <eClassifiers xsi:type="ecore:EClass" name="State" abstract="true" eSuperTypes="../../com.vectorsf.jvoice.base.model/model/Base.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingTransitions" lowerBound="1"
        upperBound="-1" eType="#//Transition" eOpposite="#//Transition/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingTransitions" lowerBound="1"
        upperBound="-1" eType="#//Transition" eOpposite="#//Transition/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="notes" eType="#//Note"
        eOpposite="#//Note/referencedStates"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="../../com.vectorsf.jvoice.base.model/model/Base.ecore#//JVElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//State" eOpposite="#//State/outgoingTransitions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//State" eOpposite="#//State/incomingTransitions"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eventName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Flow" eSuperTypes="../../com.vectorsf.jvoice.base.model/model/Base.ecore#//JVBean">
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" lowerBound="1"
        upperBound="-1" eType="#//State" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" lowerBound="1"
        upperBound="4" eType="#//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="notes" upperBound="-1"
        eType="#//Note" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beans" upperBound="-1"
        eType="#//ComponentBean" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameters" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitialState" eSuperTypes="#//State"/>
  <eClassifiers xsi:type="ecore:EClass" name="FinalState" eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnExpression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SwitchState" eSuperTypes="#//State">
    <eOperations name="getCase" eType="#//Case">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="for (Case switchCase: getCase()) {&#xD;&#xA;&#x9;if (switchCase.getEventName().equals(name)) {&#xD;&#xA;&#x9;&#x9;return switchCase;&#xD;&#xA;&#x9;}&#xD;&#xA;}&#xD;&#xA;&#x9;&#x9;&#xD;&#xA;return null;"/>
      </eAnnotations>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="case" upperBound="-1" eType="#//Case"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Case">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eventName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallState" eSuperTypes="#//ParameterizedState">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="methodName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bean" eType="#//ComponentBean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallFlowState" eSuperTypes="#//ParameterizedState">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subflow" eType="#//Flow"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PromptState" eSuperTypes="#//LocutionState"/>
  <eClassifiers xsi:type="ecore:EClass" name="InputState" eSuperTypes="#//LocutionState"/>
  <eClassifiers xsi:type="ecore:EClass" name="MenuState" eSuperTypes="#//LocutionState"/>
  <eClassifiers xsi:type="ecore:EClass" name="LocutionState" abstract="true" eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="locution" eType="ecore:EClass ../../com.vectorsf.jvoice.prompt.model/model/VoiceDsl.ecore#//VoiceDsl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransferState" eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="destination" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="audioTransfer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeout" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeTransfer" eType="#//TypeTransfer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RecordState" eSuperTypes="#//LocutionState"/>
  <eClassifiers xsi:type="ecore:EEnum" name="TypeTransfer">
    <eLiterals name="blind"/>
    <eLiterals name="consultation" value="1"/>
    <eLiterals name="bridge" value="2" literal="bridge"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Note" eSuperTypes="../../com.vectorsf.jvoice.base.model/model/Base.ecore#//JVElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedStates" upperBound="-1"
        eType="#//State" eOpposite="#//State/notes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomState" eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentBean" eSuperTypes="../../com.vectorsf.jvoice.base.model/model/Base.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fqdn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameBean" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterizedState" abstract="true"
      eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameters" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
