/**
 * generated by Xtext
 */
package com.isb.bks.ivr.voice.dsl.serializer;

import com.isb.bks.ivr.voice.dsl.serializer.AbstractVoiceDslSemanticSequencer;

@SuppressWarnings("all")
public class VoiceDslSemanticSequencer extends AbstractVoiceDslSemanticSequencer {
}
