
package org.tempuri;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2014-02-06T17:05:52.874+01:00
 * Generated source version: 2.7.8
 * 
 */
public final class ServicesSoap_ServicesSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "Services");

    private ServicesSoap_ServicesSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Services.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Services ss = new Services(wsdlURL, SERVICE_NAME);
        ServicesSoap port = ss.getServicesSoap12();  
        
        {
        System.out.println("Invoking jwServiceUlt5PagosProcPR...");
        java.lang.String _jwServiceUlt5PagosProcPR_connID = "";
        java.lang.String _jwServiceUlt5PagosProcPR_callID = "";
        java.lang.String _jwServiceUlt5PagosProcPR_nss = "";
        java.lang.String _jwServiceUlt5PagosProcPR_customerId = "";
        org.tempuri.JWServiceUlt5PagosProcPRResponse2 _jwServiceUlt5PagosProcPR__return = port.jwServiceUlt5PagosProcPR(_jwServiceUlt5PagosProcPR_connID, _jwServiceUlt5PagosProcPR_callID, _jwServiceUlt5PagosProcPR_nss, _jwServiceUlt5PagosProcPR_customerId);
        System.out.println("jwServiceUlt5PagosProcPR.result=" + _jwServiceUlt5PagosProcPR__return);


        }
        {
        System.out.println("Invoking jwServiceCtasMerchPR...");
        java.lang.String _jwServiceCtasMerchPR_connID = "";
        java.lang.String _jwServiceCtasMerchPR_callID = "";
        java.lang.String _jwServiceCtasMerchPR_customerId = "";
        java.lang.String _jwServiceCtasMerchPR_merchantId = "";
        org.tempuri.JWServiceCtasMerchPRResponse2 _jwServiceCtasMerchPR__return = port.jwServiceCtasMerchPR(_jwServiceCtasMerchPR_connID, _jwServiceCtasMerchPR_callID, _jwServiceCtasMerchPR_customerId, _jwServiceCtasMerchPR_merchantId);
        System.out.println("jwServiceCtasMerchPR.result=" + _jwServiceCtasMerchPR__return);


        }
        {
        System.out.println("Invoking jwServiceMerchantPay...");
        java.lang.String _jwServiceMerchantPay_connID = "";
        java.lang.String _jwServiceMerchantPay_callID = "";
        java.lang.String _jwServiceMerchantPay_customerId = "";
        java.lang.String _jwServiceMerchantPay_numCuenta = "";
        java.lang.String _jwServiceMerchantPay_merchantId = "";
        java.lang.String _jwServiceMerchantPay_idMerchantCta = "";
        java.lang.String _jwServiceMerchantPay_montoPay = "";
        java.lang.String _jwServiceMerchantPay_fechProcPay = "";
        org.tempuri.JWServiceMerchantPayResponse2 _jwServiceMerchantPay__return = port.jwServiceMerchantPay(_jwServiceMerchantPay_connID, _jwServiceMerchantPay_callID, _jwServiceMerchantPay_customerId, _jwServiceMerchantPay_numCuenta, _jwServiceMerchantPay_merchantId, _jwServiceMerchantPay_idMerchantCta, _jwServiceMerchantPay_montoPay, _jwServiceMerchantPay_fechProcPay);
        System.out.println("jwServiceMerchantPay.result=" + _jwServiceMerchantPay__return);


        }
        {
        System.out.println("Invoking jwServiceCtasCustPR...");
        java.lang.String _jwServiceCtasCustPR_connID = "";
        java.lang.String _jwServiceCtasCustPR_callID = "";
        java.lang.String _jwServiceCtasCustPR_customerId = "";
        java.lang.String _jwServiceCtasCustPR_idMerchantCta = "";
        org.tempuri.JWServiceCtasCustPRResponse2 _jwServiceCtasCustPR__return = port.jwServiceCtasCustPR(_jwServiceCtasCustPR_connID, _jwServiceCtasCustPR_callID, _jwServiceCtasCustPR_customerId, _jwServiceCtasCustPR_idMerchantCta);
        System.out.println("jwServiceCtasCustPR.result=" + _jwServiceCtasCustPR__return);


        }
        {
        System.out.println("Invoking jwServiceMerchListPR...");
        java.lang.String _jwServiceMerchListPR_connID = "";
        java.lang.String _jwServiceMerchListPR_callID = "";
        java.lang.String _jwServiceMerchListPR_nss = "";
        org.tempuri.JWServiceMerchListPRResponse2 _jwServiceMerchListPR__return = port.jwServiceMerchListPR(_jwServiceMerchListPR_connID, _jwServiceMerchListPR_callID, _jwServiceMerchListPR_nss);
        System.out.println("jwServiceMerchListPR.result=" + _jwServiceMerchListPR__return);


        }
        {
        System.out.println("Invoking jwServicePagosPendPR...");
        java.lang.String _jwServicePagosPendPR_connID = "";
        java.lang.String _jwServicePagosPendPR_callID = "";
        java.lang.String _jwServicePagosPendPR_nss = "";
        java.lang.String _jwServicePagosPendPR_customerId = "";
        org.tempuri.JWServicePagosPendPRResponse2 _jwServicePagosPendPR__return = port.jwServicePagosPendPR(_jwServicePagosPendPR_connID, _jwServicePagosPendPR_callID, _jwServicePagosPendPR_nss, _jwServicePagosPendPR_customerId);
        System.out.println("jwServicePagosPendPR.result=" + _jwServicePagosPendPR__return);


        }

        System.exit(0);
    }

}
