<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="IVR" nsURI="http://com.IVR.ecore" nsPrefix="IVR">
  <eClassifiers xsi:type="ecore:EClass" name="Prompt" eSuperTypes="Generic_BKS.ecore#//State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="text" eType="#//Literal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Input" eSuperTypes="Generic_BKS.ecore#//State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="text" eType="#//Literal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Menu" eSuperTypes="Generic_BKS.ecore#//State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="texts" eType="#//Literal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
