/**
 * generated by Xtext
 */
package com.isb.bks.ivr.voice.dsl.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class VoiceDslQuickfixProvider extends DefaultQuickfixProvider {
}
