/*
 * generated by Xtext
 */
package com.isb.bks.ivr.voice.dsl.validation;

import java.io.File;

import org.eclipse.core.resources.ResourcesPlugin;
import org.eclipse.core.runtime.IPath;
import org.eclipse.emf.common.util.URI;
import org.eclipse.xtext.validation.Check;

import com.vectorsf.jvoice.prompt.model.voiceDsl.Audio;
import com.vectorsf.jvoice.prompt.model.voiceDsl.VoiceDslPackage;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
public class VoiceDslJavaValidator extends com.isb.bks.ivr.voice.dsl.validation.AbstractVoiceDslJavaValidator {

	@Check
	public void checkAudioContainsProperSrc(Audio audio) {
		if (audio.getSrc() != null) {
			URI uri = audio.eResource().getURI();
			File rawFile = null;
			if (uri.isPlatformResource()) {
				IPath rawPath = ResourcesPlugin.getWorkspace().getRoot().findMember(uri.toPlatformString(true))
						.getRawLocation();

				rawFile = rawPath.toFile();
			} else {
				rawFile = new File(uri.toFileString());
			}
			File projectFile = findProjectFile(rawFile);
			File audiosFolder = new File(projectFile, "src/main/resources/audios");
			String audioName = audio.getSrc() + ".wav";
			File audioFile = new File(audiosFolder, audioName);

			if (!audioFile.exists()) {
				warning("Audio file not found", VoiceDslPackage.Literals.AUDIO__SRC);
			}
		}
	}

	private File findProjectFile(File file) {
		if (file == null) {
			return null;
		}
		if (new File(file, "src/main/resources").exists()) {
			return file;
		}
		return findProjectFile(file.getParentFile());
	}
}
