/**
 *
 * $Id$
 */
package com.vectorsf.jvoice.model.operations.validation;

import com.vectorsf.jvoice.model.operations.ComponentBean;
import com.vectorsf.jvoice.model.operations.Note;
import com.vectorsf.jvoice.model.operations.State;
import com.vectorsf.jvoice.model.operations.Transition;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.vectorsf.jvoice.model.operations.Flow}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FlowValidator {
	boolean validate();

	boolean validateStates(EList<State> value);
	boolean validateTransitions(EList<Transition> value);
	boolean validateNotes(EList<Note> value);
	boolean validateBeans(EList<ComponentBean> value);
	boolean validateParameters(EList<String> value);
}
