
package com.ivrpr.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServices", targetNamespace = "http://ws.ivrpr.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServices {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.ivrpr.ws.JwServiceAutenticaResponse2
     */
    @WebMethod(operationName = "JWServiceAutentica")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "JWServiceAutentica", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWServiceAutentica")
    @ResponseWrapper(localName = "JWServiceAutenticaResponse", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWServiceAutenticaResponse")
    @Action(input = "http://ws.ivrpr.com/WebServices/JWServiceAutenticaRequest", output = "http://ws.ivrpr.com/WebServices/JWServiceAutenticaResponse")
    public JwServiceAutenticaResponse2 jwServiceAutentica(
        @WebParam(name = "arg0", targetNamespace = "")
        JwServiceAutenticaRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ivrpr.ws.JwsprPortafolioResponse2
     */
    @WebMethod(operationName = "JWSPRPortafolio")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "JWSPRPortafolio", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWSPRPortafolio")
    @ResponseWrapper(localName = "JWSPRPortafolioResponse", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWSPRPortafolioResponse")
    @Action(input = "http://ws.ivrpr.com/WebServices/JWSPRPortafolioRequest", output = "http://ws.ivrpr.com/WebServices/JWSPRPortafolioResponse")
    public JwsprPortafolioResponse2 jwsprPortafolio(
        @WebParam(name = "arg0", targetNamespace = "")
        JwsprPortafolioRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ivrpr.ws.JwsprCambioNipResponse2
     */
    @WebMethod(operationName = "JWSPRCambioNip")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "JWSPRCambioNip", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWSPRCambioNip")
    @ResponseWrapper(localName = "JWSPRCambioNipResponse", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWSPRCambioNipResponse")
    @Action(input = "http://ws.ivrpr.com/WebServices/JWSPRCambioNipRequest", output = "http://ws.ivrpr.com/WebServices/JWSPRCambioNipResponse")
    public JwsprCambioNipResponse2 jwsprCambioNip(
        @WebParam(name = "arg0", targetNamespace = "")
        JwsprCambioNipRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ivrpr.ws.JwsprLineaReservaResponse2
     */
    @WebMethod(operationName = "JWSPRLineaReserva")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "JWSPRLineaReserva", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWSPRLineaReserva")
    @ResponseWrapper(localName = "JWSPRLineaReservaResponse", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWSPRLineaReservaResponse")
    @Action(input = "http://ws.ivrpr.com/WebServices/JWSPRLineaReservaRequest", output = "http://ws.ivrpr.com/WebServices/JWSPRLineaReservaResponse")
    public JwsprLineaReservaResponse2 jwsprLineaReserva(
        @WebParam(name = "arg0", targetNamespace = "")
        JwsprLineaReservaRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ivrpr.ws.JwsprCertDepositosResponse2
     */
    @WebMethod(operationName = "JWSPRCertDepositos")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "JWSPRCertDepositos", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWSPRCertDepositos")
    @ResponseWrapper(localName = "JWSPRCertDepositosResponse", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWSPRCertDepositosResponse")
    @Action(input = "http://ws.ivrpr.com/WebServices/JWSPRCertDepositosRequest", output = "http://ws.ivrpr.com/WebServices/JWSPRCertDepositosResponse")
    public JwsprCertDepositosResponse2 jwsprCertDepositos(
        @WebParam(name = "arg0", targetNamespace = "")
        JwsprCertDepositosRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ivrpr.ws.JwsprCtasIRAResponse2
     */
    @WebMethod(operationName = "JWSPRCtasIRA")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "JWSPRCtasIRA", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWSPRCtasIRA")
    @ResponseWrapper(localName = "JWSPRCtasIRAResponse", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWSPRCtasIRAResponse")
    @Action(input = "http://ws.ivrpr.com/WebServices/JWSPRCtasIRARequest", output = "http://ws.ivrpr.com/WebServices/JWSPRCtasIRAResponse")
    public JwsprCtasIRAResponse2 jwsprCtasIRA(
        @WebParam(name = "arg0", targetNamespace = "")
        JwsprCtasIRARequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ivrpr.ws.JwsprBalanceChequeResponse2
     */
    @WebMethod(operationName = "JWSPRBalanceCheque")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "JWSPRBalanceCheque", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWSPRBalanceCheque")
    @ResponseWrapper(localName = "JWSPRBalanceChequeResponse", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWSPRBalanceChequeResponse")
    @Action(input = "http://ws.ivrpr.com/WebServices/JWSPRBalanceChequeRequest", output = "http://ws.ivrpr.com/WebServices/JWSPRBalanceChequeResponse")
    public JwsprBalanceChequeResponse2 jwsprBalanceCheque(
        @WebParam(name = "arg0", targetNamespace = "")
        JwsprBalanceChequeRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ivrpr.ws.JwsprChequePagadoResponse2
     */
    @WebMethod(operationName = "JWSPRChequePagado")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "JWSPRChequePagado", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWSPRChequePagado")
    @ResponseWrapper(localName = "JWSPRChequePagadoResponse", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWSPRChequePagadoResponse")
    @Action(input = "http://ws.ivrpr.com/WebServices/JWSPRChequePagadoRequest", output = "http://ws.ivrpr.com/WebServices/JWSPRChequePagadoResponse")
    public JwsprChequePagadoResponse2 jwsprChequePagado(
        @WebParam(name = "arg0", targetNamespace = "")
        JwsprChequePagadoRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ivrpr.ws.JwsprMovCtasResponse2
     */
    @WebMethod(operationName = "JWSPRMovCtas")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "JWSPRMovCtas", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWSPRMovCtas")
    @ResponseWrapper(localName = "JWSPRMovCtasResponse", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWSPRMovCtasResponse")
    @Action(input = "http://ws.ivrpr.com/WebServices/JWSPRMovCtasRequest", output = "http://ws.ivrpr.com/WebServices/JWSPRMovCtasResponse")
    public JwsprMovCtasResponse2 jwsprMovCtas(
        @WebParam(name = "arg0", targetNamespace = "")
        JwsprMovCtasRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ivrpr.ws.JwsprBalanceAhorroResponse2
     */
    @WebMethod(operationName = "JWSPRBalanceAhorro")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "JWSPRBalanceAhorro", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWSPRBalanceAhorro")
    @ResponseWrapper(localName = "JWSPRBalanceAhorroResponse", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWSPRBalanceAhorroResponse")
    @Action(input = "http://ws.ivrpr.com/WebServices/JWSPRBalanceAhorroRequest", output = "http://ws.ivrpr.com/WebServices/JWSPRBalanceAhorroResponse")
    public JwsprBalanceAhorroResponse2 jwsprBalanceAhorro(
        @WebParam(name = "arg0", targetNamespace = "")
        JwsprBalanceAhorroRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ivrpr.ws.JwsprTarjetaCreditoResponse2
     */
    @WebMethod(operationName = "JWSPRTarjetaCredito")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "JWSPRTarjetaCredito", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWSPRTarjetaCredito")
    @ResponseWrapper(localName = "JWSPRTarjetaCreditoResponse", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWSPRTarjetaCreditoResponse")
    @Action(input = "http://ws.ivrpr.com/WebServices/JWSPRTarjetaCreditoRequest", output = "http://ws.ivrpr.com/WebServices/JWSPRTarjetaCreditoResponse")
    public JwsprTarjetaCreditoResponse2 jwsprTarjetaCredito(
        @WebParam(name = "arg0", targetNamespace = "")
        JwsprTarjetaCreditoRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ivrpr.ws.JwsprMovTdcResponse2
     */
    @WebMethod(operationName = "JWSPRMovTdc")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "JWSPRMovTdc", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWSPRMovTdc")
    @ResponseWrapper(localName = "JWSPRMovTdcResponse", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWSPRMovTdcResponse")
    @Action(input = "http://ws.ivrpr.com/WebServices/JWSPRMovTdcRequest", output = "http://ws.ivrpr.com/WebServices/JWSPRMovTdcResponse")
    public JwsprMovTdcResponse2 jwsprMovTdc(
        @WebParam(name = "arg0", targetNamespace = "")
        JwsprMovTdcRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ivrpr.ws.JwsprTransferCtaResponse2
     */
    @WebMethod(operationName = "JWSPRTransferCtas")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "JWSPRTransferCtas", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWSPRTransferCtas")
    @ResponseWrapper(localName = "JWSPRTransferCtasResponse", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWSPRTransferCtasResponse")
    @Action(input = "http://ws.ivrpr.com/WebServices/JWSPRTransferCtasRequest", output = "http://ws.ivrpr.com/WebServices/JWSPRTransferCtasResponse")
    public JwsprTransferCtaResponse2 jwsprTransferCtas(
        @WebParam(name = "arg0", targetNamespace = "")
        JwsprTransferCtaRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ivrpr.ws.JwsprSuspendeChequesResponse2
     */
    @WebMethod(operationName = "JWSPRSuspendeCheques")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "JWSPRSuspendeCheques", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWSPRSuspendeCheques")
    @ResponseWrapper(localName = "JWSPRSuspendeChequesResponse", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWSPRSuspendeChequesResponse")
    @Action(input = "http://ws.ivrpr.com/WebServices/JWSPRSuspendeChequesRequest", output = "http://ws.ivrpr.com/WebServices/JWSPRSuspendeChequesResponse")
    public JwsprSuspendeChequesResponse2 jwsprSuspendeCheques(
        @WebParam(name = "arg0", targetNamespace = "")
        JwsprSuspendeChequesRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ivrpr.ws.JwsprPagoTdcResponse2
     */
    @WebMethod(operationName = "JWSPRPagoTdc")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "JWSPRPagoTdc", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWSPRPagoTdc")
    @ResponseWrapper(localName = "JWSPRPagoTdcResponse", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWSPRPagoTdcResponse")
    @Action(input = "http://ws.ivrpr.com/WebServices/JWSPRPagoTdcRequest", output = "http://ws.ivrpr.com/WebServices/JWSPRPagoTdcResponse")
    public JwsprPagoTdcResponse2 jwsprPagoTdc(
        @WebParam(name = "arg0", targetNamespace = "")
        JwsprPagoTdcRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ivrpr.ws.JwServiceSPFResponse2
     */
    @WebMethod(operationName = "JWServiceSPF")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "JWServiceSPF", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWServiceSPF")
    @ResponseWrapper(localName = "JWServiceSPFResponse", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWServiceSPFResponse")
    @Action(input = "http://ws.ivrpr.com/WebServices/JWServiceSPFRequest", output = "http://ws.ivrpr.com/WebServices/JWServiceSPFResponse")
    public JwServiceSPFResponse2 jwServiceSPF(
        @WebParam(name = "arg0", targetNamespace = "")
        JwServiceSPFRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ivrpr.ws.JwsprActivacionTdcResponse2
     */
    @WebMethod(operationName = "JWSPRActivacionTdc")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "JWSPRActivacionTdc", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWSPRActivacionTdc")
    @ResponseWrapper(localName = "JWSPRActivacionTdcResponse", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWSPRActivacionTdcResponse")
    @Action(input = "http://ws.ivrpr.com/WebServices/JWSPRActivacionTdcRequest", output = "http://ws.ivrpr.com/WebServices/JWSPRActivacionTdcResponse")
    public JwsprActivacionTdcResponse2 jwsprActivacionTdc(
        @WebParam(name = "arg0", targetNamespace = "")
        JwsprActivacionTdcRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ivrpr.ws.JwServiceSegmentoResponse2
     */
    @WebMethod(operationName = "JWServiceSegmento")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "JWServiceSegmento", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWServiceSegmento")
    @ResponseWrapper(localName = "JWServiceSegmentoResponse", targetNamespace = "http://ws.ivrpr.com/", className = "com.ivrpr.ws.JWServiceSegmentoResponse")
    @Action(input = "http://ws.ivrpr.com/WebServices/JWServiceSegmentoRequest", output = "http://ws.ivrpr.com/WebServices/JWServiceSegmentoResponse")
    public JwServiceSegmentoResponse2 jwServiceSegmento(
        @WebParam(name = "arg0", targetNamespace = "")
        JwServiceSegmentoRequest arg0);

}
