/**
 * generated by Xtext
 */
package com.isb.bks.ivr.voice.dsl.validation;

import com.isb.bks.ivr.voice.dsl.validation.AbstractVoiceDslValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class VoiceDslValidator extends AbstractVoiceDslValidator {
}
