/*
 * generated by Xtext
 */
package com.isb.bks.ivr.voice.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractVoiceDslValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.isb.bks.ivr.voice.dsl.voiceDsl.VoiceDslPackage.eINSTANCE);
		return result;
	}
}
