/*
 * generated by Xtext
 */
package com.isb.bks.ivr.voice.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class VoiceDslRuntimeModule extends com.isb.bks.ivr.voice.dsl.AbstractVoiceDslRuntimeModule {

}
