/*
* generated by Xtext
*/
package com.isb.bks.ivr.voice.dsl.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.xbase.services.XbaseGrammarAccess;
import org.eclipse.xtext.xbase.services.XtypeGrammarAccess;

@Singleton
public class VoiceDslGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class VoiceDslElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "VoiceDsl");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cInputnameKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cNameAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0_1_0 = (RuleCall)cNameAssignment_0_1.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_0_2 = (UnorderedGroup)cGroup_0.eContents().get(2);
		private final Assignment cConfigurationAssignment_0_2_0 = (Assignment)cUnorderedGroup_0_2.eContents().get(0);
		private final RuleCall cConfigurationConfigurationParserRuleCall_0_2_0_0 = (RuleCall)cConfigurationAssignment_0_2_0.eContents().get(0);
		private final Assignment cGrammarsAssignment_0_2_1 = (Assignment)cUnorderedGroup_0_2.eContents().get(1);
		private final RuleCall cGrammarsGrammarsParserRuleCall_0_2_1_0 = (RuleCall)cGrammarsAssignment_0_2_1.eContents().get(0);
		private final Assignment cPropertiesAssignment_0_2_2 = (Assignment)cUnorderedGroup_0_2.eContents().get(2);
		private final RuleCall cPropertiesPropertyParserRuleCall_0_2_2_0 = (RuleCall)cPropertiesAssignment_0_2_2.eContents().get(0);
		private final Assignment cConditionsAssignment_0_2_3 = (Assignment)cUnorderedGroup_0_2.eContents().get(3);
		private final RuleCall cConditionsConditionParserRuleCall_0_2_3_0 = (RuleCall)cConditionsAssignment_0_2_3.eContents().get(0);
		private final Assignment cAudiosAssignment_0_3 = (Assignment)cGroup_0.eContents().get(3);
		private final RuleCall cAudiosAudiosParserRuleCall_0_3_0 = (RuleCall)cAudiosAssignment_0_3.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cPromptnameKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cNameAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_1_0 = (RuleCall)cNameAssignment_1_1.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_1_2 = (UnorderedGroup)cGroup_1.eContents().get(2);
		private final Assignment cPropertiesAssignment_1_2_0 = (Assignment)cUnorderedGroup_1_2.eContents().get(0);
		private final RuleCall cPropertiesPropertyParserRuleCall_1_2_0_0 = (RuleCall)cPropertiesAssignment_1_2_0.eContents().get(0);
		private final Assignment cConditionsAssignment_1_2_1 = (Assignment)cUnorderedGroup_1_2.eContents().get(1);
		private final RuleCall cConditionsConditionParserRuleCall_1_2_1_0 = (RuleCall)cConditionsAssignment_1_2_1.eContents().get(0);
		private final Assignment cAudiosAssignment_1_3 = (Assignment)cGroup_1.eContents().get(3);
		private final RuleCall cAudiosAudiosParserRuleCall_1_3_0 = (RuleCall)cAudiosAssignment_1_3.eContents().get(0);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Keyword cMenunameKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cNameAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_2_1_0 = (RuleCall)cNameAssignment_2_1.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_2_2 = (UnorderedGroup)cGroup_2.eContents().get(2);
		private final Assignment cConfigurationAssignment_2_2_0 = (Assignment)cUnorderedGroup_2_2.eContents().get(0);
		private final RuleCall cConfigurationConfigurationParserRuleCall_2_2_0_0 = (RuleCall)cConfigurationAssignment_2_2_0.eContents().get(0);
		private final Assignment cGrammarsAssignment_2_2_1 = (Assignment)cUnorderedGroup_2_2.eContents().get(1);
		private final RuleCall cGrammarsGrammarsParserRuleCall_2_2_1_0 = (RuleCall)cGrammarsAssignment_2_2_1.eContents().get(0);
		private final Assignment cPropertiesAssignment_2_2_2 = (Assignment)cUnorderedGroup_2_2.eContents().get(2);
		private final RuleCall cPropertiesPropertyParserRuleCall_2_2_2_0 = (RuleCall)cPropertiesAssignment_2_2_2.eContents().get(0);
		private final Assignment cConditionsAssignment_2_2_3 = (Assignment)cUnorderedGroup_2_2.eContents().get(3);
		private final RuleCall cConditionsConditionParserRuleCall_2_2_3_0 = (RuleCall)cConditionsAssignment_2_2_3.eContents().get(0);
		private final Assignment cOutputsAssignment_2_3 = (Assignment)cGroup_2.eContents().get(3);
		private final RuleCall cOutputsOutputsParserRuleCall_2_3_0 = (RuleCall)cOutputsAssignment_2_3.eContents().get(0);
		
		////import "http://www.isb.com/bks/ivr/voice/dsl/VoiceDsl/1.0"
		//
		////import "classpath:/model/VoiceDsl.ecore"
		//
		//VoiceDsl:
		//	"inputname" name=ID (configuration=Configuration & grammars=Grammars & properties+=Property* & conditions+=Condition*)
		//	audios=Audios | "promptname" name=ID (properties+=Property* & conditions+=Condition*) audios=Audios | "menuname"
		//	name=ID (configuration=Configuration & grammars=Grammars & properties+=Property* & conditions+=Condition*)
		//	outputs=Outputs;
		public ParserRule getRule() { return rule; }

		//"inputname" name=ID (configuration=Configuration & grammars=Grammars & properties+=Property* & conditions+=Condition*)
		//audios=Audios | "promptname" name=ID (properties+=Property* & conditions+=Condition*) audios=Audios | "menuname"
		//name=ID (configuration=Configuration & grammars=Grammars & properties+=Property* & conditions+=Condition*)
		//outputs=Outputs
		public Alternatives getAlternatives() { return cAlternatives; }

		//"inputname" name=ID (configuration=Configuration & grammars=Grammars & properties+=Property* & conditions+=Condition*)
		//audios=Audios
		public Group getGroup_0() { return cGroup_0; }

		//"inputname"
		public Keyword getInputnameKeyword_0_0() { return cInputnameKeyword_0_0; }

		//name=ID
		public Assignment getNameAssignment_0_1() { return cNameAssignment_0_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_1_0() { return cNameIDTerminalRuleCall_0_1_0; }

		//configuration=Configuration & grammars=Grammars & properties+=Property* & conditions+=Condition*
		public UnorderedGroup getUnorderedGroup_0_2() { return cUnorderedGroup_0_2; }

		//configuration=Configuration
		public Assignment getConfigurationAssignment_0_2_0() { return cConfigurationAssignment_0_2_0; }

		//Configuration
		public RuleCall getConfigurationConfigurationParserRuleCall_0_2_0_0() { return cConfigurationConfigurationParserRuleCall_0_2_0_0; }

		//grammars=Grammars
		public Assignment getGrammarsAssignment_0_2_1() { return cGrammarsAssignment_0_2_1; }

		//Grammars
		public RuleCall getGrammarsGrammarsParserRuleCall_0_2_1_0() { return cGrammarsGrammarsParserRuleCall_0_2_1_0; }

		//properties+=Property*
		public Assignment getPropertiesAssignment_0_2_2() { return cPropertiesAssignment_0_2_2; }

		//Property
		public RuleCall getPropertiesPropertyParserRuleCall_0_2_2_0() { return cPropertiesPropertyParserRuleCall_0_2_2_0; }

		//conditions+=Condition*
		public Assignment getConditionsAssignment_0_2_3() { return cConditionsAssignment_0_2_3; }

		//Condition
		public RuleCall getConditionsConditionParserRuleCall_0_2_3_0() { return cConditionsConditionParserRuleCall_0_2_3_0; }

		//audios=Audios
		public Assignment getAudiosAssignment_0_3() { return cAudiosAssignment_0_3; }

		//Audios
		public RuleCall getAudiosAudiosParserRuleCall_0_3_0() { return cAudiosAudiosParserRuleCall_0_3_0; }

		//"promptname" name=ID (properties+=Property* & conditions+=Condition*) audios=Audios
		public Group getGroup_1() { return cGroup_1; }

		//"promptname"
		public Keyword getPromptnameKeyword_1_0() { return cPromptnameKeyword_1_0; }

		//name=ID
		public Assignment getNameAssignment_1_1() { return cNameAssignment_1_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_1_0() { return cNameIDTerminalRuleCall_1_1_0; }

		//properties+=Property* & conditions+=Condition*
		public UnorderedGroup getUnorderedGroup_1_2() { return cUnorderedGroup_1_2; }

		//properties+=Property*
		public Assignment getPropertiesAssignment_1_2_0() { return cPropertiesAssignment_1_2_0; }

		//Property
		public RuleCall getPropertiesPropertyParserRuleCall_1_2_0_0() { return cPropertiesPropertyParserRuleCall_1_2_0_0; }

		//conditions+=Condition*
		public Assignment getConditionsAssignment_1_2_1() { return cConditionsAssignment_1_2_1; }

		//Condition
		public RuleCall getConditionsConditionParserRuleCall_1_2_1_0() { return cConditionsConditionParserRuleCall_1_2_1_0; }

		//audios=Audios
		public Assignment getAudiosAssignment_1_3() { return cAudiosAssignment_1_3; }

		//Audios
		public RuleCall getAudiosAudiosParserRuleCall_1_3_0() { return cAudiosAudiosParserRuleCall_1_3_0; }

		//"menuname" name=ID (configuration=Configuration & grammars=Grammars & properties+=Property* & conditions+=Condition*)
		//outputs=Outputs
		public Group getGroup_2() { return cGroup_2; }

		//"menuname"
		public Keyword getMenunameKeyword_2_0() { return cMenunameKeyword_2_0; }

		//name=ID
		public Assignment getNameAssignment_2_1() { return cNameAssignment_2_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_1_0() { return cNameIDTerminalRuleCall_2_1_0; }

		//configuration=Configuration & grammars=Grammars & properties+=Property* & conditions+=Condition*
		public UnorderedGroup getUnorderedGroup_2_2() { return cUnorderedGroup_2_2; }

		//configuration=Configuration
		public Assignment getConfigurationAssignment_2_2_0() { return cConfigurationAssignment_2_2_0; }

		//Configuration
		public RuleCall getConfigurationConfigurationParserRuleCall_2_2_0_0() { return cConfigurationConfigurationParserRuleCall_2_2_0_0; }

		//grammars=Grammars
		public Assignment getGrammarsAssignment_2_2_1() { return cGrammarsAssignment_2_2_1; }

		//Grammars
		public RuleCall getGrammarsGrammarsParserRuleCall_2_2_1_0() { return cGrammarsGrammarsParserRuleCall_2_2_1_0; }

		//properties+=Property*
		public Assignment getPropertiesAssignment_2_2_2() { return cPropertiesAssignment_2_2_2; }

		//Property
		public RuleCall getPropertiesPropertyParserRuleCall_2_2_2_0() { return cPropertiesPropertyParserRuleCall_2_2_2_0; }

		//conditions+=Condition*
		public Assignment getConditionsAssignment_2_2_3() { return cConditionsAssignment_2_2_3; }

		//Condition
		public RuleCall getConditionsConditionParserRuleCall_2_2_3_0() { return cConditionsConditionParserRuleCall_2_2_3_0; }

		//outputs=Outputs
		public Assignment getOutputsAssignment_2_3() { return cOutputsAssignment_2_3; }

		//Outputs
		public RuleCall getOutputsOutputsParserRuleCall_2_3_0() { return cOutputsOutputsParserRuleCall_2_3_0; }
	}

	public class GrammarsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Grammars");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGrammarsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cGrammaticsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cGrammaticsGrammarParserRuleCall_2_0 = (RuleCall)cGrammaticsAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Grammars:
		//	"grammars" "{" grammatics+=Grammar* "}";
		public ParserRule getRule() { return rule; }

		//"grammars" "{" grammatics+=Grammar* "}"
		public Group getGroup() { return cGroup; }

		//"grammars"
		public Keyword getGrammarsKeyword_0() { return cGrammarsKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//grammatics+=Grammar*
		public Assignment getGrammaticsAssignment_2() { return cGrammaticsAssignment_2; }

		//Grammar
		public RuleCall getGrammaticsGrammarParserRuleCall_2_0() { return cGrammaticsGrammarParserRuleCall_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}

	public class AudiosElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Audios");
		private final UnorderedGroup cUnorderedGroup = (UnorderedGroup)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cUnorderedGroup.eContents().get(0);
		private final Keyword cAudiosKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Group cGroup_0_2 = (Group)cGroup_0.eContents().get(2);
		private final Keyword cMainKeyword_0_2_0 = (Keyword)cGroup_0_2.eContents().get(0);
		private final Keyword cColonKeyword_0_2_1 = (Keyword)cGroup_0_2.eContents().get(1);
		private final Assignment cMainAudiosAssignment_0_2_2 = (Assignment)cGroup_0_2.eContents().get(2);
		private final RuleCall cMainAudiosConditionalAudioParserRuleCall_0_2_2_0 = (RuleCall)cMainAudiosAssignment_0_2_2.eContents().get(0);
		private final Group cGroup_1 = (Group)cUnorderedGroup.eContents().get(1);
		private final Keyword cMatchKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Keyword cColonKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cMatchAudiosAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cMatchAudiosConditionalAudioParserRuleCall_1_2_0 = (RuleCall)cMatchAudiosAssignment_1_2.eContents().get(0);
		private final Group cGroup_2 = (Group)cUnorderedGroup.eContents().get(2);
		private final Keyword cNomatchKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Keyword cColonKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Assignment cNoMatchAudiosAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cNoMatchAudiosConditionalAudioParserRuleCall_2_2_0 = (RuleCall)cNoMatchAudiosAssignment_2_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cUnorderedGroup.eContents().get(3);
		private final Group cGroup_3_0 = (Group)cGroup_3.eContents().get(0);
		private final Keyword cNoinputKeyword_3_0_0 = (Keyword)cGroup_3_0.eContents().get(0);
		private final Keyword cColonKeyword_3_0_1 = (Keyword)cGroup_3_0.eContents().get(1);
		private final Assignment cNoInputAudiosAssignment_3_0_2 = (Assignment)cGroup_3_0.eContents().get(2);
		private final RuleCall cNoInputAudiosConditionalAudioParserRuleCall_3_0_2_0 = (RuleCall)cNoInputAudiosAssignment_3_0_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		
		//Audios:
		//	"audios" "{" ("main" ":" mainAudios+=ConditionalAudio+)? & ("match" ":" matchAudios+=ConditionalAudio+)? & ("nomatch"
		//	":" noMatchAudios+=ConditionalAudio+)? & ("noinput" ":" noInputAudios+=ConditionalAudio+)? "}";
		public ParserRule getRule() { return rule; }

		//"audios" "{" ("main" ":" mainAudios+=ConditionalAudio+)? & ("match" ":" matchAudios+=ConditionalAudio+)? & ("nomatch"
		//":" noMatchAudios+=ConditionalAudio+)? & ("noinput" ":" noInputAudios+=ConditionalAudio+)? "}"
		public UnorderedGroup getUnorderedGroup() { return cUnorderedGroup; }

		//"audios" "{" ("main" ":" mainAudios+=ConditionalAudio+)?
		public Group getGroup_0() { return cGroup_0; }

		//"audios"
		public Keyword getAudiosKeyword_0_0() { return cAudiosKeyword_0_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_0_1() { return cLeftCurlyBracketKeyword_0_1; }

		//("main" ":" mainAudios+=ConditionalAudio+)?
		public Group getGroup_0_2() { return cGroup_0_2; }

		//"main"
		public Keyword getMainKeyword_0_2_0() { return cMainKeyword_0_2_0; }

		//":"
		public Keyword getColonKeyword_0_2_1() { return cColonKeyword_0_2_1; }

		//mainAudios+=ConditionalAudio+
		public Assignment getMainAudiosAssignment_0_2_2() { return cMainAudiosAssignment_0_2_2; }

		//ConditionalAudio
		public RuleCall getMainAudiosConditionalAudioParserRuleCall_0_2_2_0() { return cMainAudiosConditionalAudioParserRuleCall_0_2_2_0; }

		//("match" ":" matchAudios+=ConditionalAudio+)?
		public Group getGroup_1() { return cGroup_1; }

		//"match"
		public Keyword getMatchKeyword_1_0() { return cMatchKeyword_1_0; }

		//":"
		public Keyword getColonKeyword_1_1() { return cColonKeyword_1_1; }

		//matchAudios+=ConditionalAudio+
		public Assignment getMatchAudiosAssignment_1_2() { return cMatchAudiosAssignment_1_2; }

		//ConditionalAudio
		public RuleCall getMatchAudiosConditionalAudioParserRuleCall_1_2_0() { return cMatchAudiosConditionalAudioParserRuleCall_1_2_0; }

		//("nomatch" ":" noMatchAudios+=ConditionalAudio+)?
		public Group getGroup_2() { return cGroup_2; }

		//"nomatch"
		public Keyword getNomatchKeyword_2_0() { return cNomatchKeyword_2_0; }

		//":"
		public Keyword getColonKeyword_2_1() { return cColonKeyword_2_1; }

		//noMatchAudios+=ConditionalAudio+
		public Assignment getNoMatchAudiosAssignment_2_2() { return cNoMatchAudiosAssignment_2_2; }

		//ConditionalAudio
		public RuleCall getNoMatchAudiosConditionalAudioParserRuleCall_2_2_0() { return cNoMatchAudiosConditionalAudioParserRuleCall_2_2_0; }

		//("noinput" ":" noInputAudios+=ConditionalAudio+)? "}"
		public Group getGroup_3() { return cGroup_3; }

		//("noinput" ":" noInputAudios+=ConditionalAudio+)?
		public Group getGroup_3_0() { return cGroup_3_0; }

		//"noinput"
		public Keyword getNoinputKeyword_3_0_0() { return cNoinputKeyword_3_0_0; }

		//":"
		public Keyword getColonKeyword_3_0_1() { return cColonKeyword_3_0_1; }

		//noInputAudios+=ConditionalAudio+
		public Assignment getNoInputAudiosAssignment_3_0_2() { return cNoInputAudiosAssignment_3_0_2; }

		//ConditionalAudio
		public RuleCall getNoInputAudiosConditionalAudioParserRuleCall_3_0_2_0() { return cNoInputAudiosConditionalAudioParserRuleCall_3_0_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3_1() { return cRightCurlyBracketKeyword_3_1; }
	}

	public class ConfigurationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Configuration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cConfigurationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cConfigValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cConfigValueConfigValueParserRuleCall_2_0 = (RuleCall)cConfigValueAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Configuration:
		//	"configuration" "{" configValue+=ConfigValue* "}";
		public ParserRule getRule() { return rule; }

		//"configuration" "{" configValue+=ConfigValue* "}"
		public Group getGroup() { return cGroup; }

		//"configuration"
		public Keyword getConfigurationKeyword_0() { return cConfigurationKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//configValue+=ConfigValue*
		public Assignment getConfigValueAssignment_2() { return cConfigValueAssignment_2; }

		//ConfigValue
		public RuleCall getConfigValueConfigValueParserRuleCall_2_0() { return cConfigValueConfigValueParserRuleCall_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}

	public class ConfigValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ConfigValue");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValueConfigValueValueParserRuleCall_1_0 = (RuleCall)cValueAssignment_1.eContents().get(0);
		
		//ConfigValue:
		//	name=ID value=ConfigValueValue;
		public ParserRule getRule() { return rule; }

		//name=ID value=ConfigValueValue
		public Group getGroup() { return cGroup; }

		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }

		//value=ConfigValueValue
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }

		//ConfigValueValue
		public RuleCall getValueConfigValueValueParserRuleCall_1_0() { return cValueConfigValueValueParserRuleCall_1_0; }
	}

	public class ConfigValueValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ConfigValueValue");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_0_0 = (RuleCall)cGroup_0.eContents().get(0);
		private final Keyword cMsKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final RuleCall cFLOATTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final Keyword cTrueKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cFalseKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		
		//ConfigValueValue:
		//	INT "ms"? | FLOAT | "true" | "false";
		public ParserRule getRule() { return rule; }

		//INT "ms"? | FLOAT | "true" | "false"
		public Alternatives getAlternatives() { return cAlternatives; }

		//INT "ms"?
		public Group getGroup_0() { return cGroup_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_0_0() { return cINTTerminalRuleCall_0_0; }

		//"ms"?
		public Keyword getMsKeyword_0_1() { return cMsKeyword_0_1; }

		//FLOAT
		public RuleCall getFLOATTerminalRuleCall_1() { return cFLOATTerminalRuleCall_1; }

		//"true"
		public Keyword getTrueKeyword_2() { return cTrueKeyword_2; }

		//"false"
		public Keyword getFalseKeyword_3() { return cFalseKeyword_3; }
	}

	public class GrammarElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Grammar");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cModeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Alternatives cModeAlternatives_0_0 = (Alternatives)cModeAssignment_0.eContents().get(0);
		private final Keyword cModeVoiceKeyword_0_0_0 = (Keyword)cModeAlternatives_0_0.eContents().get(0);
		private final Keyword cModeDtmfKeyword_0_0_1 = (Keyword)cModeAlternatives_0_0.eContents().get(1);
		private final Keyword cModeVoicedtmfKeyword_0_0_2 = (Keyword)cModeAlternatives_0_0.eContents().get(2);
		private final Assignment cExprAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cExprExprKeyword_1_0 = (Keyword)cExprAssignment_1.eContents().get(0);
		private final Assignment cSrcAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cSrcSTRINGTerminalRuleCall_2_0 = (RuleCall)cSrcAssignment_2.eContents().get(0);
		
		//Grammar:
		//	mode=("voice" | "dtmf" | "voicedtmf") expr?="expr"? src=STRING;
		public ParserRule getRule() { return rule; }

		//mode=("voice" | "dtmf" | "voicedtmf") expr?="expr"? src=STRING
		public Group getGroup() { return cGroup; }

		//mode=("voice" | "dtmf" | "voicedtmf")
		public Assignment getModeAssignment_0() { return cModeAssignment_0; }

		//"voice" | "dtmf" | "voicedtmf"
		public Alternatives getModeAlternatives_0_0() { return cModeAlternatives_0_0; }

		//"voice"
		public Keyword getModeVoiceKeyword_0_0_0() { return cModeVoiceKeyword_0_0_0; }

		//"dtmf"
		public Keyword getModeDtmfKeyword_0_0_1() { return cModeDtmfKeyword_0_0_1; }

		//"voicedtmf"
		public Keyword getModeVoicedtmfKeyword_0_0_2() { return cModeVoicedtmfKeyword_0_0_2; }

		//expr?="expr"?
		public Assignment getExprAssignment_1() { return cExprAssignment_1; }

		//"expr"
		public Keyword getExprExprKeyword_1_0() { return cExprExprKeyword_1_0; }

		//src=STRING
		public Assignment getSrcAssignment_2() { return cSrcAssignment_2; }

		//STRING
		public RuleCall getSrcSTRINGTerminalRuleCall_2_0() { return cSrcSTRINGTerminalRuleCall_2_0; }
	}

	public class PropertyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Property");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPropertyKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameQualifiedNameParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueSTRINGTerminalRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		
		//Property:
		//	"property" name=QualifiedName value=STRING;
		public ParserRule getRule() { return rule; }

		//"property" name=QualifiedName value=STRING
		public Group getGroup() { return cGroup; }

		//"property"
		public Keyword getPropertyKeyword_0() { return cPropertyKeyword_0; }

		//name=QualifiedName
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//QualifiedName
		public RuleCall getNameQualifiedNameParserRuleCall_1_0() { return cNameQualifiedNameParserRuleCall_1_0; }

		//value=STRING
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }

		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_2_0() { return cValueSTRINGTerminalRuleCall_2_0; }
	}

	public class ConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Condition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cConditionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cConditionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Assignment cConditionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cConditionINTTerminalRuleCall_3_0 = (RuleCall)cConditionAssignment_3.eContents().get(0);
		
		//Condition:
		//	{Condition} "condition" name=ID condition=INT;
		public ParserRule getRule() { return rule; }

		//{Condition} "condition" name=ID condition=INT
		public Group getGroup() { return cGroup; }

		//{Condition}
		public Action getConditionAction_0() { return cConditionAction_0; }

		//"condition"
		public Keyword getConditionKeyword_1() { return cConditionKeyword_1; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//condition=INT
		public Assignment getConditionAssignment_3() { return cConditionAssignment_3; }

		//INT
		public RuleCall getConditionINTTerminalRuleCall_3_0() { return cConditionINTTerminalRuleCall_3_0; }
	}

	public class OutputsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Outputs");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOutputsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cOutputAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cOutputOutputParserRuleCall_2_0 = (RuleCall)cOutputAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Outputs:
		//	"outputs" "{" output+=Output+ "}";
		public ParserRule getRule() { return rule; }

		//"outputs" "{" output+=Output+ "}"
		public Group getGroup() { return cGroup; }

		//"outputs"
		public Keyword getOutputsKeyword_0() { return cOutputsKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//output+=Output+
		public Assignment getOutputAssignment_2() { return cOutputAssignment_2; }

		//Output
		public RuleCall getOutputOutputParserRuleCall_2_0() { return cOutputOutputParserRuleCall_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}

	public class OutputElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Output");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cOutputValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cOutputValueOutputValueParserRuleCall_2_0 = (RuleCall)cOutputValueAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCommaKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cOutputValueAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cOutputValueOutputValueParserRuleCall_3_1_0 = (RuleCall)cOutputValueAssignment_3_1.eContents().get(0);
		
		//Output:
		//	name=ID ":" outputValue+=OutputValue ("," outputValue+=OutputValue)*;
		public ParserRule getRule() { return rule; }

		//name=ID ":" outputValue+=OutputValue ("," outputValue+=OutputValue)*
		public Group getGroup() { return cGroup; }

		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }

		//":"
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }

		//outputValue+=OutputValue
		public Assignment getOutputValueAssignment_2() { return cOutputValueAssignment_2; }

		//OutputValue
		public RuleCall getOutputValueOutputValueParserRuleCall_2_0() { return cOutputValueOutputValueParserRuleCall_2_0; }

		//("," outputValue+=OutputValue)*
		public Group getGroup_3() { return cGroup_3; }

		//","
		public Keyword getCommaKeyword_3_0() { return cCommaKeyword_3_0; }

		//outputValue+=OutputValue
		public Assignment getOutputValueAssignment_3_1() { return cOutputValueAssignment_3_1; }

		//OutputValue
		public RuleCall getOutputValueOutputValueParserRuleCall_3_1_0() { return cOutputValueOutputValueParserRuleCall_3_1_0; }
	}

	public class OutputValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "OutputValue");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cValueAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cValueSTRINGTerminalRuleCall_0_0 = (RuleCall)cValueAssignment_0.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final Keyword cValueAsteriskKeyword_1_0 = (Keyword)cValueAssignment_1.eContents().get(0);
		
		//OutputValue:
		//	value=STRING | value="*";
		public ParserRule getRule() { return rule; }

		//value=STRING | value="*"
		public Alternatives getAlternatives() { return cAlternatives; }

		//value=STRING
		public Assignment getValueAssignment_0() { return cValueAssignment_0; }

		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_0_0() { return cValueSTRINGTerminalRuleCall_0_0; }

		//value="*"
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }

		//"*"
		public Keyword getValueAsteriskKeyword_1_0() { return cValueAsteriskKeyword_1_0; }
	}

	public class SimpleAudioElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SimpleAudio");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAudioAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSayKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Group cGroup_2_0 = (Group)cGroup_2.eContents().get(0);
		private final Keyword cSrcKeyword_2_0_0 = (Keyword)cGroup_2_0.eContents().get(0);
		private final Assignment cSrcAssignment_2_0_1 = (Assignment)cGroup_2_0.eContents().get(1);
		private final RuleCall cSrcSTRINGTerminalRuleCall_2_0_1_0 = (RuleCall)cSrcAssignment_2_0_1.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cGroup_2.eContents().get(1);
		private final Keyword cWordingKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Assignment cTtsAssignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final RuleCall cTtsSTRINGTerminalRuleCall_2_1_1_0 = (RuleCall)cTtsAssignment_2_1_1.eContents().get(0);
		
		//SimpleAudio returns Audio:
		//	{Audio} "say" (("src" src=STRING)? ("wording" tts=STRING)?);
		public ParserRule getRule() { return rule; }

		//{Audio} "say" (("src" src=STRING)? ("wording" tts=STRING)?)
		public Group getGroup() { return cGroup; }

		//{Audio}
		public Action getAudioAction_0() { return cAudioAction_0; }

		//"say"
		public Keyword getSayKeyword_1() { return cSayKeyword_1; }

		//("src" src=STRING)? ("wording" tts=STRING)?
		public Group getGroup_2() { return cGroup_2; }

		//("src" src=STRING)?
		public Group getGroup_2_0() { return cGroup_2_0; }

		//"src"
		public Keyword getSrcKeyword_2_0_0() { return cSrcKeyword_2_0_0; }

		//src=STRING
		public Assignment getSrcAssignment_2_0_1() { return cSrcAssignment_2_0_1; }

		//STRING
		public RuleCall getSrcSTRINGTerminalRuleCall_2_0_1_0() { return cSrcSTRINGTerminalRuleCall_2_0_1_0; }

		//("wording" tts=STRING)?
		public Group getGroup_2_1() { return cGroup_2_1; }

		//"wording"
		public Keyword getWordingKeyword_2_1_0() { return cWordingKeyword_2_1_0; }

		//tts=STRING
		public Assignment getTtsAssignment_2_1_1() { return cTtsAssignment_2_1_1; }

		//STRING
		public RuleCall getTtsSTRINGTerminalRuleCall_2_1_1_0() { return cTtsSTRINGTerminalRuleCall_2_1_1_0; }
	}

	public class ConditionalAudioElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ConditionalAudio");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cConditionalAudioAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Keyword cWhenKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Assignment cConditAssignment_0_3 = (Assignment)cGroup_0.eContents().get(3);
		private final RuleCall cConditXExpressionParserRuleCall_0_3_0 = (RuleCall)cConditAssignment_0_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_0_4 = (Keyword)cGroup_0.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_0_5 = (Keyword)cGroup_0.eContents().get(5);
		private final Assignment cSimpleAAssignment_0_6 = (Assignment)cGroup_0.eContents().get(6);
		private final RuleCall cSimpleASimpleAudioParserRuleCall_0_6_0 = (RuleCall)cSimpleAAssignment_0_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_0_7 = (Keyword)cGroup_0.eContents().get(7);
		private final RuleCall cSimpleAudioParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//ConditionalAudio returns Audio:
		//	{ConditionalAudio} "when" "(" condit=XExpression ")" "{" simpleA=SimpleAudio+ "}" | SimpleAudio;
		public ParserRule getRule() { return rule; }

		//{ConditionalAudio} "when" "(" condit=XExpression ")" "{" simpleA=SimpleAudio+ "}" | SimpleAudio
		public Alternatives getAlternatives() { return cAlternatives; }

		//{ConditionalAudio} "when" "(" condit=XExpression ")" "{" simpleA=SimpleAudio+ "}"
		public Group getGroup_0() { return cGroup_0; }

		//{ConditionalAudio}
		public Action getConditionalAudioAction_0_0() { return cConditionalAudioAction_0_0; }

		//"when"
		public Keyword getWhenKeyword_0_1() { return cWhenKeyword_0_1; }

		//"("
		public Keyword getLeftParenthesisKeyword_0_2() { return cLeftParenthesisKeyword_0_2; }

		//condit=XExpression
		public Assignment getConditAssignment_0_3() { return cConditAssignment_0_3; }

		//XExpression
		public RuleCall getConditXExpressionParserRuleCall_0_3_0() { return cConditXExpressionParserRuleCall_0_3_0; }

		//")"
		public Keyword getRightParenthesisKeyword_0_4() { return cRightParenthesisKeyword_0_4; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_0_5() { return cLeftCurlyBracketKeyword_0_5; }

		//simpleA=SimpleAudio+
		public Assignment getSimpleAAssignment_0_6() { return cSimpleAAssignment_0_6; }

		//SimpleAudio
		public RuleCall getSimpleASimpleAudioParserRuleCall_0_6_0() { return cSimpleASimpleAudioParserRuleCall_0_6_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_0_7() { return cRightCurlyBracketKeyword_0_7; }

		//SimpleAudio
		public RuleCall getSimpleAudioParserRuleCall_1() { return cSimpleAudioParserRuleCall_1; }
	}
	
	
	private VoiceDslElements pVoiceDsl;
	private GrammarsElements pGrammars;
	private AudiosElements pAudios;
	private ConfigurationElements pConfiguration;
	private ConfigValueElements pConfigValue;
	private ConfigValueValueElements pConfigValueValue;
	private GrammarElements pGrammar;
	private PropertyElements pProperty;
	private ConditionElements pCondition;
	private OutputsElements pOutputs;
	private OutputElements pOutput;
	private OutputValueElements pOutputValue;
	private SimpleAudioElements pSimpleAudio;
	private ConditionalAudioElements pConditionalAudio;
	private TerminalRule tFLOAT;
	
	private final Grammar grammar;

	private XbaseGrammarAccess gaXbase;

	@Inject
	public VoiceDslGrammarAccess(GrammarProvider grammarProvider,
		XbaseGrammarAccess gaXbase) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaXbase = gaXbase;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("com.isb.bks.ivr.voice.dsl.VoiceDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public XbaseGrammarAccess getXbaseGrammarAccess() {
		return gaXbase;
	}

	
	////import "http://www.isb.com/bks/ivr/voice/dsl/VoiceDsl/1.0"
	//
	////import "classpath:/model/VoiceDsl.ecore"
	//
	//VoiceDsl:
	//	"inputname" name=ID (configuration=Configuration & grammars=Grammars & properties+=Property* & conditions+=Condition*)
	//	audios=Audios | "promptname" name=ID (properties+=Property* & conditions+=Condition*) audios=Audios | "menuname"
	//	name=ID (configuration=Configuration & grammars=Grammars & properties+=Property* & conditions+=Condition*)
	//	outputs=Outputs;
	public VoiceDslElements getVoiceDslAccess() {
		return (pVoiceDsl != null) ? pVoiceDsl : (pVoiceDsl = new VoiceDslElements());
	}
	
	public ParserRule getVoiceDslRule() {
		return getVoiceDslAccess().getRule();
	}

	//Grammars:
	//	"grammars" "{" grammatics+=Grammar* "}";
	public GrammarsElements getGrammarsAccess() {
		return (pGrammars != null) ? pGrammars : (pGrammars = new GrammarsElements());
	}
	
	public ParserRule getGrammarsRule() {
		return getGrammarsAccess().getRule();
	}

	//Audios:
	//	"audios" "{" ("main" ":" mainAudios+=ConditionalAudio+)? & ("match" ":" matchAudios+=ConditionalAudio+)? & ("nomatch"
	//	":" noMatchAudios+=ConditionalAudio+)? & ("noinput" ":" noInputAudios+=ConditionalAudio+)? "}";
	public AudiosElements getAudiosAccess() {
		return (pAudios != null) ? pAudios : (pAudios = new AudiosElements());
	}
	
	public ParserRule getAudiosRule() {
		return getAudiosAccess().getRule();
	}

	//Configuration:
	//	"configuration" "{" configValue+=ConfigValue* "}";
	public ConfigurationElements getConfigurationAccess() {
		return (pConfiguration != null) ? pConfiguration : (pConfiguration = new ConfigurationElements());
	}
	
	public ParserRule getConfigurationRule() {
		return getConfigurationAccess().getRule();
	}

	//ConfigValue:
	//	name=ID value=ConfigValueValue;
	public ConfigValueElements getConfigValueAccess() {
		return (pConfigValue != null) ? pConfigValue : (pConfigValue = new ConfigValueElements());
	}
	
	public ParserRule getConfigValueRule() {
		return getConfigValueAccess().getRule();
	}

	//ConfigValueValue:
	//	INT "ms"? | FLOAT | "true" | "false";
	public ConfigValueValueElements getConfigValueValueAccess() {
		return (pConfigValueValue != null) ? pConfigValueValue : (pConfigValueValue = new ConfigValueValueElements());
	}
	
	public ParserRule getConfigValueValueRule() {
		return getConfigValueValueAccess().getRule();
	}

	//Grammar:
	//	mode=("voice" | "dtmf" | "voicedtmf") expr?="expr"? src=STRING;
	public GrammarElements getGrammarAccess() {
		return (pGrammar != null) ? pGrammar : (pGrammar = new GrammarElements());
	}
	
	public ParserRule getGrammarRule() {
		return getGrammarAccess().getRule();
	}

	//Property:
	//	"property" name=QualifiedName value=STRING;
	public PropertyElements getPropertyAccess() {
		return (pProperty != null) ? pProperty : (pProperty = new PropertyElements());
	}
	
	public ParserRule getPropertyRule() {
		return getPropertyAccess().getRule();
	}

	//Condition:
	//	{Condition} "condition" name=ID condition=INT;
	public ConditionElements getConditionAccess() {
		return (pCondition != null) ? pCondition : (pCondition = new ConditionElements());
	}
	
	public ParserRule getConditionRule() {
		return getConditionAccess().getRule();
	}

	//Outputs:
	//	"outputs" "{" output+=Output+ "}";
	public OutputsElements getOutputsAccess() {
		return (pOutputs != null) ? pOutputs : (pOutputs = new OutputsElements());
	}
	
	public ParserRule getOutputsRule() {
		return getOutputsAccess().getRule();
	}

	//Output:
	//	name=ID ":" outputValue+=OutputValue ("," outputValue+=OutputValue)*;
	public OutputElements getOutputAccess() {
		return (pOutput != null) ? pOutput : (pOutput = new OutputElements());
	}
	
	public ParserRule getOutputRule() {
		return getOutputAccess().getRule();
	}

	//OutputValue:
	//	value=STRING | value="*";
	public OutputValueElements getOutputValueAccess() {
		return (pOutputValue != null) ? pOutputValue : (pOutputValue = new OutputValueElements());
	}
	
	public ParserRule getOutputValueRule() {
		return getOutputValueAccess().getRule();
	}

	//SimpleAudio returns Audio:
	//	{Audio} "say" (("src" src=STRING)? ("wording" tts=STRING)?);
	public SimpleAudioElements getSimpleAudioAccess() {
		return (pSimpleAudio != null) ? pSimpleAudio : (pSimpleAudio = new SimpleAudioElements());
	}
	
	public ParserRule getSimpleAudioRule() {
		return getSimpleAudioAccess().getRule();
	}

	//ConditionalAudio returns Audio:
	//	{ConditionalAudio} "when" "(" condit=XExpression ")" "{" simpleA=SimpleAudio+ "}" | SimpleAudio;
	public ConditionalAudioElements getConditionalAudioAccess() {
		return (pConditionalAudio != null) ? pConditionalAudio : (pConditionalAudio = new ConditionalAudioElements());
	}
	
	public ParserRule getConditionalAudioRule() {
		return getConditionalAudioAccess().getRule();
	}

	//terminal FLOAT:
	//	INT "." INT;
	public TerminalRule getFLOATRule() {
		return (tFLOAT != null) ? tFLOAT : (tFLOAT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "FLOAT"));
	} 

	//XExpression:
	//	XAssignment;
	public XbaseGrammarAccess.XExpressionElements getXExpressionAccess() {
		return gaXbase.getXExpressionAccess();
	}
	
	public ParserRule getXExpressionRule() {
		return getXExpressionAccess().getRule();
	}

	//XAssignment returns XExpression:
	//	{XAssignment} feature=[types::JvmIdentifiableElement|FeatureCallID] OpSingleAssign value=XAssignment | XOrExpression
	//	(=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpMultiAssign])
	//	rightOperand=XAssignment)?;
	public XbaseGrammarAccess.XAssignmentElements getXAssignmentAccess() {
		return gaXbase.getXAssignmentAccess();
	}
	
	public ParserRule getXAssignmentRule() {
		return getXAssignmentAccess().getRule();
	}

	//OpSingleAssign:
	//	"=";
	public XbaseGrammarAccess.OpSingleAssignElements getOpSingleAssignAccess() {
		return gaXbase.getOpSingleAssignAccess();
	}
	
	public ParserRule getOpSingleAssignRule() {
		return getOpSingleAssignAccess().getRule();
	}

	//OpMultiAssign:
	//	"+=" | "-=";
	public XbaseGrammarAccess.OpMultiAssignElements getOpMultiAssignAccess() {
		return gaXbase.getOpMultiAssignAccess();
	}
	
	public ParserRule getOpMultiAssignRule() {
		return getOpMultiAssignAccess().getRule();
	}

	//XOrExpression returns XExpression:
	//	XAndExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpOr])
	//	rightOperand=XAndExpression)*;
	public XbaseGrammarAccess.XOrExpressionElements getXOrExpressionAccess() {
		return gaXbase.getXOrExpressionAccess();
	}
	
	public ParserRule getXOrExpressionRule() {
		return getXOrExpressionAccess().getRule();
	}

	//OpOr:
	//	"||";
	public XbaseGrammarAccess.OpOrElements getOpOrAccess() {
		return gaXbase.getOpOrAccess();
	}
	
	public ParserRule getOpOrRule() {
		return getOpOrAccess().getRule();
	}

	//XAndExpression returns XExpression:
	//	XEqualityExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpAnd])
	//	rightOperand=XEqualityExpression)*;
	public XbaseGrammarAccess.XAndExpressionElements getXAndExpressionAccess() {
		return gaXbase.getXAndExpressionAccess();
	}
	
	public ParserRule getXAndExpressionRule() {
		return getXAndExpressionAccess().getRule();
	}

	//OpAnd:
	//	"&&";
	public XbaseGrammarAccess.OpAndElements getOpAndAccess() {
		return gaXbase.getOpAndAccess();
	}
	
	public ParserRule getOpAndRule() {
		return getOpAndAccess().getRule();
	}

	//XEqualityExpression returns XExpression:
	//	XRelationalExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpEquality])
	//	rightOperand=XRelationalExpression)*;
	public XbaseGrammarAccess.XEqualityExpressionElements getXEqualityExpressionAccess() {
		return gaXbase.getXEqualityExpressionAccess();
	}
	
	public ParserRule getXEqualityExpressionRule() {
		return getXEqualityExpressionAccess().getRule();
	}

	//OpEquality:
	//	"==" | "!=" | "===" | "!==";
	public XbaseGrammarAccess.OpEqualityElements getOpEqualityAccess() {
		return gaXbase.getOpEqualityAccess();
	}
	
	public ParserRule getOpEqualityRule() {
		return getOpEqualityAccess().getRule();
	}

	//XRelationalExpression returns XExpression:
	//	XOtherOperatorExpression (=> ({XInstanceOfExpression.expression=current} "instanceof") type=JvmTypeReference | =>
	//	({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpCompare])
	//	rightOperand=XOtherOperatorExpression)*;
	public XbaseGrammarAccess.XRelationalExpressionElements getXRelationalExpressionAccess() {
		return gaXbase.getXRelationalExpressionAccess();
	}
	
	public ParserRule getXRelationalExpressionRule() {
		return getXRelationalExpressionAccess().getRule();
	}

	//OpCompare:
	//	">=" | "<=" | ">" | "<";
	public XbaseGrammarAccess.OpCompareElements getOpCompareAccess() {
		return gaXbase.getOpCompareAccess();
	}
	
	public ParserRule getOpCompareRule() {
		return getOpCompareAccess().getRule();
	}

	//XOtherOperatorExpression returns XExpression:
	//	XAdditiveExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpOther])
	//	rightOperand=XAdditiveExpression)*;
	public XbaseGrammarAccess.XOtherOperatorExpressionElements getXOtherOperatorExpressionAccess() {
		return gaXbase.getXOtherOperatorExpressionAccess();
	}
	
	public ParserRule getXOtherOperatorExpressionRule() {
		return getXOtherOperatorExpressionAccess().getRule();
	}

	//OpOther:
	//	"->" | "..<" | ">" ".." | ".." | "=>" | ">" (=> (">" ">") | ">") | "<" (=> ("<" "<") | "<") | "<>" | "?:" | "<=>";
	public XbaseGrammarAccess.OpOtherElements getOpOtherAccess() {
		return gaXbase.getOpOtherAccess();
	}
	
	public ParserRule getOpOtherRule() {
		return getOpOtherAccess().getRule();
	}

	//XAdditiveExpression returns XExpression:
	//	XMultiplicativeExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpAdd])
	//	rightOperand=XMultiplicativeExpression)*;
	public XbaseGrammarAccess.XAdditiveExpressionElements getXAdditiveExpressionAccess() {
		return gaXbase.getXAdditiveExpressionAccess();
	}
	
	public ParserRule getXAdditiveExpressionRule() {
		return getXAdditiveExpressionAccess().getRule();
	}

	//OpAdd:
	//	"+" | "-";
	public XbaseGrammarAccess.OpAddElements getOpAddAccess() {
		return gaXbase.getOpAddAccess();
	}
	
	public ParserRule getOpAddRule() {
		return getOpAddAccess().getRule();
	}

	//XMultiplicativeExpression returns XExpression:
	//	XUnaryOperation (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpMulti])
	//	rightOperand=XUnaryOperation)*;
	public XbaseGrammarAccess.XMultiplicativeExpressionElements getXMultiplicativeExpressionAccess() {
		return gaXbase.getXMultiplicativeExpressionAccess();
	}
	
	public ParserRule getXMultiplicativeExpressionRule() {
		return getXMultiplicativeExpressionAccess().getRule();
	}

	//OpMulti:
	//	"*" | "**" | "/" | "%";
	public XbaseGrammarAccess.OpMultiElements getOpMultiAccess() {
		return gaXbase.getOpMultiAccess();
	}
	
	public ParserRule getOpMultiRule() {
		return getOpMultiAccess().getRule();
	}

	//XUnaryOperation returns XExpression:
	//	{XUnaryOperation} feature=[types::JvmIdentifiableElement|OpUnary] operand=XUnaryOperation | XCastedExpression;
	public XbaseGrammarAccess.XUnaryOperationElements getXUnaryOperationAccess() {
		return gaXbase.getXUnaryOperationAccess();
	}
	
	public ParserRule getXUnaryOperationRule() {
		return getXUnaryOperationAccess().getRule();
	}

	//OpUnary:
	//	"!" | "-" | "+";
	public XbaseGrammarAccess.OpUnaryElements getOpUnaryAccess() {
		return gaXbase.getOpUnaryAccess();
	}
	
	public ParserRule getOpUnaryRule() {
		return getOpUnaryAccess().getRule();
	}

	//XCastedExpression returns XExpression:
	//	XMemberFeatureCall (=> ({XCastedExpression.target=current} "as") type=JvmTypeReference)*;
	public XbaseGrammarAccess.XCastedExpressionElements getXCastedExpressionAccess() {
		return gaXbase.getXCastedExpressionAccess();
	}
	
	public ParserRule getXCastedExpressionRule() {
		return getXCastedExpressionAccess().getRule();
	}

	//XMemberFeatureCall returns XExpression:
	//	XPrimaryExpression (=> ({XAssignment.assignable=current} ("." | explicitStatic?="::")
	//	feature=[types::JvmIdentifiableElement|FeatureCallID] OpSingleAssign) value=XAssignment | =>
	//	({XMemberFeatureCall.memberCallTarget=current} ("." | nullSafe?="?." | explicitStatic?="::")) ("<"
	//	typeArguments+=JvmArgumentTypeReference ("," typeArguments+=JvmArgumentTypeReference)* ">")?
	//	feature=[types::JvmIdentifiableElement|FeatureCallID] (=> explicitOperationCall?="("
	//	(memberCallArguments+=XShortClosure | memberCallArguments+=XExpression ("," memberCallArguments+=XExpression)*)? ")")?
	//	memberCallArguments+=XClosure?)*;
	public XbaseGrammarAccess.XMemberFeatureCallElements getXMemberFeatureCallAccess() {
		return gaXbase.getXMemberFeatureCallAccess();
	}
	
	public ParserRule getXMemberFeatureCallRule() {
		return getXMemberFeatureCallAccess().getRule();
	}

	//XPrimaryExpression returns XExpression:
	//	XConstructorCall | XBlockExpression | XSwitchExpression | XFeatureCall | XLiteral | XIfExpression | XForLoopExpression
	//	| XWhileExpression | XDoWhileExpression | XThrowExpression | XReturnExpression | XTryCatchFinallyExpression |
	//	XParenthesizedExpression;
	public XbaseGrammarAccess.XPrimaryExpressionElements getXPrimaryExpressionAccess() {
		return gaXbase.getXPrimaryExpressionAccess();
	}
	
	public ParserRule getXPrimaryExpressionRule() {
		return getXPrimaryExpressionAccess().getRule();
	}

	//XLiteral returns XExpression:
	//	XCollectionLiteral | XClosure | XBooleanLiteral | XNumberLiteral | XNullLiteral | XStringLiteral | XTypeLiteral;
	public XbaseGrammarAccess.XLiteralElements getXLiteralAccess() {
		return gaXbase.getXLiteralAccess();
	}
	
	public ParserRule getXLiteralRule() {
		return getXLiteralAccess().getRule();
	}

	//XCollectionLiteral:
	//	XSetLiteral | XListLiteral;
	public XbaseGrammarAccess.XCollectionLiteralElements getXCollectionLiteralAccess() {
		return gaXbase.getXCollectionLiteralAccess();
	}
	
	public ParserRule getXCollectionLiteralRule() {
		return getXCollectionLiteralAccess().getRule();
	}

	//XSetLiteral:
	//	{XSetLiteral} "#" "{" (elements+=XExpression ("," elements+=XExpression)*)? "}";
	public XbaseGrammarAccess.XSetLiteralElements getXSetLiteralAccess() {
		return gaXbase.getXSetLiteralAccess();
	}
	
	public ParserRule getXSetLiteralRule() {
		return getXSetLiteralAccess().getRule();
	}

	//XListLiteral:
	//	{XListLiteral} "#" "[" (elements+=XExpression ("," elements+=XExpression)*)? "]";
	public XbaseGrammarAccess.XListLiteralElements getXListLiteralAccess() {
		return gaXbase.getXListLiteralAccess();
	}
	
	public ParserRule getXListLiteralRule() {
		return getXListLiteralAccess().getRule();
	}

	//XClosure returns XExpression:
	//	=> ({XClosure} "[") => ((declaredFormalParameters+=JvmFormalParameter (","
	//	declaredFormalParameters+=JvmFormalParameter)*)? explicitSyntax?="|")? expression=XExpressionInClosure "]";
	public XbaseGrammarAccess.XClosureElements getXClosureAccess() {
		return gaXbase.getXClosureAccess();
	}
	
	public ParserRule getXClosureRule() {
		return getXClosureAccess().getRule();
	}

	//XExpressionInClosure returns XExpression:
	//	{XBlockExpression} (expressions+=XExpressionInsideBlock ";"?)*;
	public XbaseGrammarAccess.XExpressionInClosureElements getXExpressionInClosureAccess() {
		return gaXbase.getXExpressionInClosureAccess();
	}
	
	public ParserRule getXExpressionInClosureRule() {
		return getXExpressionInClosureAccess().getRule();
	}

	//XShortClosure returns XExpression:
	//	=> ({XClosure} (declaredFormalParameters+=JvmFormalParameter ("," declaredFormalParameters+=JvmFormalParameter)*)?
	//	explicitSyntax?="|") expression=XExpression;
	public XbaseGrammarAccess.XShortClosureElements getXShortClosureAccess() {
		return gaXbase.getXShortClosureAccess();
	}
	
	public ParserRule getXShortClosureRule() {
		return getXShortClosureAccess().getRule();
	}

	//XParenthesizedExpression returns XExpression:
	//	"(" XExpression ")";
	public XbaseGrammarAccess.XParenthesizedExpressionElements getXParenthesizedExpressionAccess() {
		return gaXbase.getXParenthesizedExpressionAccess();
	}
	
	public ParserRule getXParenthesizedExpressionRule() {
		return getXParenthesizedExpressionAccess().getRule();
	}

	//XIfExpression returns XExpression:
	//	{XIfExpression} "if" "(" if=XExpression ")" then=XExpression ("else" else=XExpression)?;
	public XbaseGrammarAccess.XIfExpressionElements getXIfExpressionAccess() {
		return gaXbase.getXIfExpressionAccess();
	}
	
	public ParserRule getXIfExpressionRule() {
		return getXIfExpressionAccess().getRule();
	}

	//XSwitchExpression returns XExpression:
	//	{XSwitchExpression} "switch" (=> (localVarName=ValidID ":")? switch=XExpression | => ("(" localVarName=ValidID ":")
	//	switch=XExpression ")") "{" cases+=XCasePart+ ("default" ":" default=XExpression)? "}";
	public XbaseGrammarAccess.XSwitchExpressionElements getXSwitchExpressionAccess() {
		return gaXbase.getXSwitchExpressionAccess();
	}
	
	public ParserRule getXSwitchExpressionRule() {
		return getXSwitchExpressionAccess().getRule();
	}

	//XCasePart:
	//	typeGuard=JvmTypeReference? ("case" case=XExpression)? ":" then=XExpression;
	public XbaseGrammarAccess.XCasePartElements getXCasePartAccess() {
		return gaXbase.getXCasePartAccess();
	}
	
	public ParserRule getXCasePartRule() {
		return getXCasePartAccess().getRule();
	}

	//XForLoopExpression returns XExpression:
	//	{XForLoopExpression} "for" "(" declaredParam=JvmFormalParameter ":" forExpression=XExpression ")"
	//	eachExpression=XExpression;
	public XbaseGrammarAccess.XForLoopExpressionElements getXForLoopExpressionAccess() {
		return gaXbase.getXForLoopExpressionAccess();
	}
	
	public ParserRule getXForLoopExpressionRule() {
		return getXForLoopExpressionAccess().getRule();
	}

	//XWhileExpression returns XExpression:
	//	{XWhileExpression} "while" "(" predicate=XExpression ")" body=XExpression;
	public XbaseGrammarAccess.XWhileExpressionElements getXWhileExpressionAccess() {
		return gaXbase.getXWhileExpressionAccess();
	}
	
	public ParserRule getXWhileExpressionRule() {
		return getXWhileExpressionAccess().getRule();
	}

	//XDoWhileExpression returns XExpression:
	//	{XDoWhileExpression} "do" body=XExpression "while" "(" predicate=XExpression ")";
	public XbaseGrammarAccess.XDoWhileExpressionElements getXDoWhileExpressionAccess() {
		return gaXbase.getXDoWhileExpressionAccess();
	}
	
	public ParserRule getXDoWhileExpressionRule() {
		return getXDoWhileExpressionAccess().getRule();
	}

	//XBlockExpression returns XExpression:
	//	{XBlockExpression} "{" (expressions+=XExpressionInsideBlock ";"?)* "}";
	public XbaseGrammarAccess.XBlockExpressionElements getXBlockExpressionAccess() {
		return gaXbase.getXBlockExpressionAccess();
	}
	
	public ParserRule getXBlockExpressionRule() {
		return getXBlockExpressionAccess().getRule();
	}

	//XExpressionInsideBlock returns XExpression:
	//	XVariableDeclaration | XExpression;
	public XbaseGrammarAccess.XExpressionInsideBlockElements getXExpressionInsideBlockAccess() {
		return gaXbase.getXExpressionInsideBlockAccess();
	}
	
	public ParserRule getXExpressionInsideBlockRule() {
		return getXExpressionInsideBlockAccess().getRule();
	}

	//XVariableDeclaration returns XExpression:
	//	{XVariableDeclaration} (writeable?="var" | "val") (=> (type=JvmTypeReference name=ValidID) | name=ValidID) ("="
	//	right=XExpression)?;
	public XbaseGrammarAccess.XVariableDeclarationElements getXVariableDeclarationAccess() {
		return gaXbase.getXVariableDeclarationAccess();
	}
	
	public ParserRule getXVariableDeclarationRule() {
		return getXVariableDeclarationAccess().getRule();
	}

	//JvmFormalParameter returns types::JvmFormalParameter:
	//	parameterType=JvmTypeReference? name=ValidID;
	public XbaseGrammarAccess.JvmFormalParameterElements getJvmFormalParameterAccess() {
		return gaXbase.getJvmFormalParameterAccess();
	}
	
	public ParserRule getJvmFormalParameterRule() {
		return getJvmFormalParameterAccess().getRule();
	}

	//FullJvmFormalParameter returns types::JvmFormalParameter:
	//	parameterType=JvmTypeReference name=ValidID;
	public XbaseGrammarAccess.FullJvmFormalParameterElements getFullJvmFormalParameterAccess() {
		return gaXbase.getFullJvmFormalParameterAccess();
	}
	
	public ParserRule getFullJvmFormalParameterRule() {
		return getFullJvmFormalParameterAccess().getRule();
	}

	//XFeatureCall returns XExpression:
	//	{XFeatureCall} ("<" typeArguments+=JvmArgumentTypeReference ("," typeArguments+=JvmArgumentTypeReference)* ">")?
	//	feature=[types::JvmIdentifiableElement|IdOrSuper] (=> explicitOperationCall?="(" (featureCallArguments+=XShortClosure
	//	| featureCallArguments+=XExpression ("," featureCallArguments+=XExpression)*)? ")")? featureCallArguments+=XClosure?;
	public XbaseGrammarAccess.XFeatureCallElements getXFeatureCallAccess() {
		return gaXbase.getXFeatureCallAccess();
	}
	
	public ParserRule getXFeatureCallRule() {
		return getXFeatureCallAccess().getRule();
	}

	//FeatureCallID:
	//	ValidID | "extends" | "static" | "import" | "extension";
	public XbaseGrammarAccess.FeatureCallIDElements getFeatureCallIDAccess() {
		return gaXbase.getFeatureCallIDAccess();
	}
	
	public ParserRule getFeatureCallIDRule() {
		return getFeatureCallIDAccess().getRule();
	}

	//IdOrSuper:
	//	FeatureCallID | "super";
	public XbaseGrammarAccess.IdOrSuperElements getIdOrSuperAccess() {
		return gaXbase.getIdOrSuperAccess();
	}
	
	public ParserRule getIdOrSuperRule() {
		return getIdOrSuperAccess().getRule();
	}

	//XConstructorCall returns XExpression:
	//	{XConstructorCall} "new" constructor=[types::JvmConstructor|QualifiedName] ("<"
	//	typeArguments+=JvmArgumentTypeReference ("," typeArguments+=JvmArgumentTypeReference)* ">")? ("("
	//	(arguments+=XShortClosure | arguments+=XExpression ("," arguments+=XExpression)*)? ")")? arguments+=XClosure?;
	public XbaseGrammarAccess.XConstructorCallElements getXConstructorCallAccess() {
		return gaXbase.getXConstructorCallAccess();
	}
	
	public ParserRule getXConstructorCallRule() {
		return getXConstructorCallAccess().getRule();
	}

	//XBooleanLiteral returns XExpression:
	//	{XBooleanLiteral} ("false" | isTrue?="true");
	public XbaseGrammarAccess.XBooleanLiteralElements getXBooleanLiteralAccess() {
		return gaXbase.getXBooleanLiteralAccess();
	}
	
	public ParserRule getXBooleanLiteralRule() {
		return getXBooleanLiteralAccess().getRule();
	}

	//XNullLiteral returns XExpression:
	//	{XNullLiteral} "null";
	public XbaseGrammarAccess.XNullLiteralElements getXNullLiteralAccess() {
		return gaXbase.getXNullLiteralAccess();
	}
	
	public ParserRule getXNullLiteralRule() {
		return getXNullLiteralAccess().getRule();
	}

	//XNumberLiteral returns XExpression:
	//	{XNumberLiteral} value=Number;
	public XbaseGrammarAccess.XNumberLiteralElements getXNumberLiteralAccess() {
		return gaXbase.getXNumberLiteralAccess();
	}
	
	public ParserRule getXNumberLiteralRule() {
		return getXNumberLiteralAccess().getRule();
	}

	//XStringLiteral returns XExpression:
	//	{XStringLiteral} value=STRING;
	public XbaseGrammarAccess.XStringLiteralElements getXStringLiteralAccess() {
		return gaXbase.getXStringLiteralAccess();
	}
	
	public ParserRule getXStringLiteralRule() {
		return getXStringLiteralAccess().getRule();
	}

	//XTypeLiteral returns XExpression:
	//	{XTypeLiteral} "typeof" "(" type=[types::JvmType|QualifiedName] arrayDimensions+=ArrayBrackets* ")";
	public XbaseGrammarAccess.XTypeLiteralElements getXTypeLiteralAccess() {
		return gaXbase.getXTypeLiteralAccess();
	}
	
	public ParserRule getXTypeLiteralRule() {
		return getXTypeLiteralAccess().getRule();
	}

	//XThrowExpression returns XExpression:
	//	{XThrowExpression} "throw" expression=XExpression;
	public XbaseGrammarAccess.XThrowExpressionElements getXThrowExpressionAccess() {
		return gaXbase.getXThrowExpressionAccess();
	}
	
	public ParserRule getXThrowExpressionRule() {
		return getXThrowExpressionAccess().getRule();
	}

	//XReturnExpression returns XExpression:
	//	{XReturnExpression} "return" => expression=XExpression?;
	public XbaseGrammarAccess.XReturnExpressionElements getXReturnExpressionAccess() {
		return gaXbase.getXReturnExpressionAccess();
	}
	
	public ParserRule getXReturnExpressionRule() {
		return getXReturnExpressionAccess().getRule();
	}

	//XTryCatchFinallyExpression returns XExpression:
	//	{XTryCatchFinallyExpression} "try" expression=XExpression (catchClauses+=XCatchClause+ ("finally"
	//	finallyExpression=XExpression)? | "finally" finallyExpression=XExpression);
	public XbaseGrammarAccess.XTryCatchFinallyExpressionElements getXTryCatchFinallyExpressionAccess() {
		return gaXbase.getXTryCatchFinallyExpressionAccess();
	}
	
	public ParserRule getXTryCatchFinallyExpressionRule() {
		return getXTryCatchFinallyExpressionAccess().getRule();
	}

	//XCatchClause:
	//	"catch" "(" declaredParam=FullJvmFormalParameter ")" expression=XExpression;
	public XbaseGrammarAccess.XCatchClauseElements getXCatchClauseAccess() {
		return gaXbase.getXCatchClauseAccess();
	}
	
	public ParserRule getXCatchClauseRule() {
		return getXCatchClauseAccess().getRule();
	}

	//QualifiedName:
	//	ValidID ("." ValidID)*;
	public XbaseGrammarAccess.QualifiedNameElements getQualifiedNameAccess() {
		return gaXbase.getQualifiedNameAccess();
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}

	//Number hidden():
	//	HEX | (INT | DECIMAL) ("." (INT | DECIMAL))?;
	public XbaseGrammarAccess.NumberElements getNumberAccess() {
		return gaXbase.getNumberAccess();
	}
	
	public ParserRule getNumberRule() {
		return getNumberAccess().getRule();
	}

	/// **
	// * Dummy rule, for "better" downwards compatibility, since GrammarAccess generates non-static inner classes, 
	// * which makes downstream grammars break on classloading, when a rule is removed.
	// * / StaticQualifier:
	//	(ValidID "::")+;
	public XbaseGrammarAccess.StaticQualifierElements getStaticQualifierAccess() {
		return gaXbase.getStaticQualifierAccess();
	}
	
	public ParserRule getStaticQualifierRule() {
		return getStaticQualifierAccess().getRule();
	}

	//terminal HEX:
	//	("0x" | "0X") ("0".."9" | "a".."f" | "A".."F" | "_")+ ("#" (("b" | "B") ("i" | "I") | ("l" | "L")))?;
	public TerminalRule getHEXRule() {
		return gaXbase.getHEXRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9" ("0".."9" | "_")*;
	public TerminalRule getINTRule() {
		return gaXbase.getINTRule();
	} 

	//terminal DECIMAL:
	//	INT (("e" | "E") ("+" | "-")? INT)? (("b" | "B") ("i" | "I" | "d" | "D") | ("l" | "L" | "d" | "D" | "f" | "F"))?;
	public TerminalRule getDECIMALRule() {
		return gaXbase.getDECIMALRule();
	} 

	//JvmTypeReference:
	//	JvmParameterizedTypeReference => ({JvmGenericArrayTypeReference.componentType=current} ArrayBrackets)* |
	//	XFunctionTypeRef;
	public XtypeGrammarAccess.JvmTypeReferenceElements getJvmTypeReferenceAccess() {
		return gaXbase.getJvmTypeReferenceAccess();
	}
	
	public ParserRule getJvmTypeReferenceRule() {
		return getJvmTypeReferenceAccess().getRule();
	}

	//ArrayBrackets:
	//	"[" "]";
	public XtypeGrammarAccess.ArrayBracketsElements getArrayBracketsAccess() {
		return gaXbase.getArrayBracketsAccess();
	}
	
	public ParserRule getArrayBracketsRule() {
		return getArrayBracketsAccess().getRule();
	}

	//XFunctionTypeRef:
	//	("(" (paramTypes+=JvmTypeReference ("," paramTypes+=JvmTypeReference)*)? ")")? "=>" returnType=JvmTypeReference;
	public XtypeGrammarAccess.XFunctionTypeRefElements getXFunctionTypeRefAccess() {
		return gaXbase.getXFunctionTypeRefAccess();
	}
	
	public ParserRule getXFunctionTypeRefRule() {
		return getXFunctionTypeRefAccess().getRule();
	}

	//JvmParameterizedTypeReference:
	//	type=[JvmType|QualifiedName] ("<" arguments+=JvmArgumentTypeReference ("," arguments+=JvmArgumentTypeReference)*
	//	">")?;
	public XtypeGrammarAccess.JvmParameterizedTypeReferenceElements getJvmParameterizedTypeReferenceAccess() {
		return gaXbase.getJvmParameterizedTypeReferenceAccess();
	}
	
	public ParserRule getJvmParameterizedTypeReferenceRule() {
		return getJvmParameterizedTypeReferenceAccess().getRule();
	}

	//JvmArgumentTypeReference returns JvmTypeReference:
	//	JvmTypeReference | JvmWildcardTypeReference;
	public XtypeGrammarAccess.JvmArgumentTypeReferenceElements getJvmArgumentTypeReferenceAccess() {
		return gaXbase.getJvmArgumentTypeReferenceAccess();
	}
	
	public ParserRule getJvmArgumentTypeReferenceRule() {
		return getJvmArgumentTypeReferenceAccess().getRule();
	}

	//JvmWildcardTypeReference:
	//	{JvmWildcardTypeReference} "?" (constraints+=JvmUpperBound | constraints+=JvmLowerBound)?;
	public XtypeGrammarAccess.JvmWildcardTypeReferenceElements getJvmWildcardTypeReferenceAccess() {
		return gaXbase.getJvmWildcardTypeReferenceAccess();
	}
	
	public ParserRule getJvmWildcardTypeReferenceRule() {
		return getJvmWildcardTypeReferenceAccess().getRule();
	}

	//JvmUpperBound:
	//	"extends" typeReference=JvmTypeReference;
	public XtypeGrammarAccess.JvmUpperBoundElements getJvmUpperBoundAccess() {
		return gaXbase.getJvmUpperBoundAccess();
	}
	
	public ParserRule getJvmUpperBoundRule() {
		return getJvmUpperBoundAccess().getRule();
	}

	//JvmUpperBoundAnded returns JvmUpperBound:
	//	"&" typeReference=JvmTypeReference;
	public XtypeGrammarAccess.JvmUpperBoundAndedElements getJvmUpperBoundAndedAccess() {
		return gaXbase.getJvmUpperBoundAndedAccess();
	}
	
	public ParserRule getJvmUpperBoundAndedRule() {
		return getJvmUpperBoundAndedAccess().getRule();
	}

	//JvmLowerBound:
	//	"super" typeReference=JvmTypeReference;
	public XtypeGrammarAccess.JvmLowerBoundElements getJvmLowerBoundAccess() {
		return gaXbase.getJvmLowerBoundAccess();
	}
	
	public ParserRule getJvmLowerBoundRule() {
		return getJvmLowerBoundAccess().getRule();
	}

	//JvmTypeParameter:
	//	name=ValidID (constraints+=JvmUpperBound constraints+=JvmUpperBoundAnded* | constraints+=JvmLowerBound)?;
	public XtypeGrammarAccess.JvmTypeParameterElements getJvmTypeParameterAccess() {
		return gaXbase.getJvmTypeParameterAccess();
	}
	
	public ParserRule getJvmTypeParameterRule() {
		return getJvmTypeParameterAccess().getRule();
	}

	//QualifiedNameWithWildcard:
	//	QualifiedName "." "*";
	public XtypeGrammarAccess.QualifiedNameWithWildcardElements getQualifiedNameWithWildcardAccess() {
		return gaXbase.getQualifiedNameWithWildcardAccess();
	}
	
	public ParserRule getQualifiedNameWithWildcardRule() {
		return getQualifiedNameWithWildcardAccess().getRule();
	}

	//ValidID:
	//	ID;
	public XtypeGrammarAccess.ValidIDElements getValidIDAccess() {
		return gaXbase.getValidIDAccess();
	}
	
	public ParserRule getValidIDRule() {
		return getValidIDAccess().getRule();
	}

	//XImportSection:
	//	importDeclarations+=XImportDeclaration+;
	public XtypeGrammarAccess.XImportSectionElements getXImportSectionAccess() {
		return gaXbase.getXImportSectionAccess();
	}
	
	public ParserRule getXImportSectionRule() {
		return getXImportSectionAccess().getRule();
	}

	//XImportDeclaration:
	//	"import" (static?="static" extension?="extension"? importedType=[JvmDeclaredType|QualifiedName] "." "*" |
	//	importedType=[JvmDeclaredType|QualifiedName] | importedNamespace=QualifiedNameWithWildcard) ";"?;
	public XtypeGrammarAccess.XImportDeclarationElements getXImportDeclarationAccess() {
		return gaXbase.getXImportDeclarationAccess();
	}
	
	public ParserRule getXImportDeclarationRule() {
		return getXImportDeclarationAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "$" | "_") ("a".."z" | "A".."Z" | "$" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaXbase.getIDRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaXbase.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaXbase.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaXbase.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaXbase.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaXbase.getANY_OTHERRule();
	} 
}
