/**
 *
 * $Id$
 */
package types.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.xtext.common.types.JvmAnnotationType;
import org.eclipse.xtext.common.types.JvmAnnotationValue;

/**
 * A sample validator interface for {@link org.eclipse.xtext.common.types.JvmAnnotationReference}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface JvmAnnotationReferenceValidator {
	boolean validate();

	boolean validateAnnotation(JvmAnnotationType value);
	boolean validateValues(EList<JvmAnnotationValue> value);
}
