/**
 *
 * $Id$
 */
package types.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.xtext.common.types.JvmTypeConstraint;

/**
 * A sample validator interface for {@link org.eclipse.xtext.common.types.JvmConstraintOwner}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface JvmConstraintOwnerValidator {
	boolean validate();

	boolean validateConstraints(EList<JvmTypeConstraint> value);
}
