/**
 *
 * $Id$
 */
package types.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.xtext.common.types.JvmMember;
import org.eclipse.xtext.common.types.JvmTypeReference;

/**
 * A sample validator interface for {@link org.eclipse.xtext.common.types.JvmDeclaredType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface JvmDeclaredTypeValidator {
	boolean validate();

	boolean validateSuperTypes(EList<JvmTypeReference> value);
	boolean validateMembers(EList<JvmMember> value);
	boolean validateAbstract(boolean value);
	boolean validateStatic(boolean value);
	boolean validateFinal(boolean value);
	boolean validatePackageName(String value);
}
