/**
 *
 * $Id$
 */
package types.validation;

import org.eclipse.xtext.common.types.JvmTypeReference;

/**
 * A sample validator interface for {@link org.eclipse.xtext.common.types.JvmFormalParameter}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface JvmFormalParameterValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateParameterType(JvmTypeReference value);
}
