/**
 *
 * $Id$
 */
package types.validation;

import org.eclipse.xtext.common.types.JvmAnnotationValue;
import org.eclipse.xtext.common.types.JvmTypeReference;

/**
 * A sample validator interface for {@link org.eclipse.xtext.common.types.JvmOperation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface JvmOperationValidator {
	boolean validate();

	boolean validateStatic(boolean value);
	boolean validateFinal(boolean value);
	boolean validateAbstract(boolean value);
	boolean validateReturnType(JvmTypeReference value);
	boolean validateDefaultValue(JvmAnnotationValue value);
	boolean validateSynchronized(boolean value);
	boolean validateDefault(boolean value);
	boolean validateNative(boolean value);
	boolean validateStrictFloatingPoint(boolean value);
}
