/**
 *
 * $Id$
 */
package types.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.xtext.common.types.JvmType;
import org.eclipse.xtext.common.types.JvmTypeReference;

/**
 * A sample validator interface for {@link org.eclipse.xtext.common.types.JvmParameterizedTypeReference}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface JvmParameterizedTypeReferenceValidator {
	boolean validate();

	boolean validateArguments(EList<JvmTypeReference> value);
	boolean validateType(JvmType value);
}
